- .template-lintrc.js
- package.json
Will help keep templates clean, used in `ember-osf`.
> Add template linting

- app/adapters/preprint.js
- app/serializers/preprint.js
Allow a node to be converted into a preprint.
Modify adapter and serializer to support unique requirements for this endpoint:
1. Custom URLS
2. Custom relationship payload, including what seems to be a special key not matching a field name
Assess whether this allows editing of an existing preprint. (editing primary file or subjects, etc)
See the ticket for notes about the workflow from the API standpoint. Below is a deliberately crude code snippet I used in a local demo route, to test whether this worked. Key requirements are an existing file, a valid subject, and explicitly passing the `id` parameter = the GUID of the originating node that will become a preprint.
(the latter is used for the serializer)
In the route:
```handlebars
<button {{action 'registerPreprint' model.node model.file …
```
> Allow conversion of node into preprint

- app/serializers/preprint.js
Fixes bug pointed out by [comment in #21](https://github.com/CenterForOpenScience/ember-preprints/pull/21/files#diff-ea08ccd8a33b794610a037162feb43d5R8) that relationship field name was odd. Relationship field name should now be passed to match name of primary_file in preprint serializer (was before relying on the type field).
**Note!** This PR relies on merging https://github.com/CenterForOpenScience/osf.io/pull/6141 which fixes the preprint relationship parser to look at the appropriate keys instead of relying on the type passed in with data
> Update payload to match new parser for file relationship

- app/components/preprint-form-section.js
- app/controllers/add-preprint.js
- app/templates/add-preprint.hbs
- app/templates/components/preprint-form-project-select.hbs
- Added comments here and there
- Added checkbox to decide whether to create child component
- Added functionality to create child component
- [EOSF-138: Adapter: Dirty Relationships don't fire requests until second save attempt](https://openscience.atlassian.net/browse/EOSF-138)
- [EOSF-139: Change return value](https://openscience.atlassian.net/browse/EOSF-139) of `NodeActionsMixin.actions.addChild` to child
Part of https://openscience.atlassian.net/browse/PREP-92
> [blockers] Add option to create child components, part of [PREP-92]

- app/components/taxonomy-top-list.js
- app/routes/index.js
- app/styles/app.scss
- app/templates/components/taxonomy-top-list.hbs
- app/templates/index.hbs
- tests/integration/components/taxonomy-top-list-test.js
Show top-level subjects as intended in the wireframe. Sorts the received taxonomies and links each one to a `discover` page with the subject name as the search query (there is no way to filter by subject in the `discover` page).
- Pull list of top-level subjects from apiv2 in index route
- New component for taxonomy listing, to ease merge conflicts
- Added styling for subject buttons
- [PREP-82: Implement search page interactions](https://openscience.atlassian.net/browse/PREP-82), links to new `discover` route, which will break the component/index page if not present
- Will not show up unless on `osf.io/ember-preprints` branch until taxonomy api is merged
https://openscience.atlassian.net/browse/PREP-106
> Load top level subjects into the index page and show them in two colums [PREP-106]

- app/controllers/submit.js
https://openscience.atlassian.net/browse/PREP-117
Fix issue where `doi:` was being allowed as prefix in doi field.
The regex could be tweaked to require at least one character after the slash, but we're going for consistency and simplicity here.
Make regex [more similar](https://github.com/abought/osf.io/blob/ce9cc6b7fe31620928ce6168a8cbba4bd3592a30/website/project/model.py#L772-L772) to what backend allows.
> [quick][rfr] Change DOI regex to be closer to backend

- app/templates/submit.hbs
Restore tags widget to submit page. (OSF-style widget rather than comma-delimited text field)
Since this was already merged and reviewed, and disappeared only due to a regression, I'll go ahead and add it back in.
> Fix tags widget regression.

- app/components/subject-picker/component.js
Fix a bug with the subject selector on submit page
1. Select a subject at the first and second levels of the taxonomy.
2. Select a third-level subject
3. Select a different second level subject
4. Select the original second-level subject. Note that the third-level section does not update with correct children.
> Fix issue with subject selector

- app/controllers/discover.js
- app/templates/components/search-result.hbs
Fix issue reported by Caner on homepage preprints provider display. Will let @hmoco test whether this also works on discover page.
After
> Fix homepage providers display issue

- app/components/preprint-form-header.js
- app/components/preprint-form-section.js
- app/controllers/submit.js
- app/routes/submit.js
- app/styles/app.scss
- app/templates/components/preprint-form-header.hbs
- app/templates/components/preprint-form-section.hbs
- app/templates/submit.hbs
Don't show an error icon (bad data) if the user hasn't even visited that panel yet.
Of course, this does mean we will want some additional validation before the user clicks submit- if they skip a section, they could end up sending bad data to the server without realizing it, because the empty field was on a tab that never ran validators to show a checkmark for (eg server will allow an empty abstract even though UI doesn't)... 
Not sure where the best place in the UI is for a "final validation check", though. @caneruguz ?
> [rfr] Fix styling of validation indicators on submit page

- app/components/preprint-form-section.js
- app/controllers/submit.js
- app/styles/app.scss
- app/styles/authors.scss
- app/templates/components/preprint-form-header.hbs
- app/templates/submit.hbs
> WIP/Feature Submit Form Polishing

- app/components/preprint-form-authors.js
- app/components/supplementary-file-browser.js
**note** Relies on CenterForOpenScience/ember-osf#125
and later: https://github.com/CenterForOpenScience/osf.io/pull/6218
Proposed changes in https://github.com/CenterForOpenScience/ember-osf/pull/125 allows you to pass along a send_email=false query parameter to the OSF API that will allow preprint contributor emails to be sent only after the preprint process has been completed.
This PR sends the signal through the addContributor method, whic on ember OSf side will send the right API request that then will trigger the emails proposed in the OSF PR that the authors have been added to a *preprint* as opposed to a confusing project!
> Use proposed changes to ember OSF's addContributor method

- app/components/supplementary-file-browser.js
OSF API v2 does not currently support filtering the file provider list, so we were getting all storage options. This sets the provider manually by looking through the provider list for 
- Use ember `findBy` instead of an API filter to only get files from osfstorage
https://trello.com/c/yDkOiFju/58-attaching-add-on-folder-breaks-preprint
> Set fileprovider manually on ember side

- app/components/author-link/component.js
- app/components/author-link/template.hbs
- app/mixins/reset-scroll.js
- app/templates/components/preprint-form-header.hbs
- app/templates/content.hbs
Fix whitespace around author and tag names on the submit page (header previews) and detail page (authors list) by applying handlebars whitespace control syntax.
https://trello.com/c/oRldPiU4/64-whitespace-between-commas-on-tags-and-authors-on-submit-page
> [rfr] Fix whitespace in comma separated lists on authors, tags

- app/templates/components/search-result.hbs
- app/templates/content.hbs
1. Improve search result display on `/discover` page
2. Change authors to display with `first Last` consistently across pages- don't use different fields or different orders
3. Right align date on search results for now. I'll defer visual tweaks to @caneruguz 's talents.
- Change how author names are displayed. Where possible, use `firstName lastName` format in place of `fullName` or `last, first`.
- The `fullName` field in the OSF is intended for profile display; individual name fields are intended to provide more fine-grained control over how name is shown.
https://trello.com/c/6fD8lRQ6/60-improve-layout-of-search-results
Formatting of the preprint summaries could be refined. 
- ~~Top-left alignment for title~~ (seems to already be like this?)
- ? No commas after names if the “|” is …
> [quick] Search result layout and author name order

- app/components/supplementary-file-browser.js
- app/controllers/content.js
- app/templates/content.hbs
Let download button on preprint view page provide the correct download link for the file currently selected in the file picker.
https://trello.com/c/SkGOyIWO/93-download-button-should-download-the-currently-selected-file
> View page file download button should match the file picker

- app/models/taxonomy.js
This was changed in the OSF/APIv2 in https://github.com/CenterForOpenScience/osf.io/pull/6178 (see [class definition](https://github.com/CenterForOpenScience/osf.io/pull/6178/files#diff-a85760ce1808ddd67ece5978b7a52534L11)), but seems to have not been used here. Updated anyway.
Before:
After:
> Update Taxonomy model

- app/templates/content.hbs
1. Show the DOI on the article page if a DOI is provided
2. Link to the article via the crossref DOI resolver service
Article with DOI:
Article without a DOI:
> If the article author provides a DOI, show it on the view page

- app/components/taxonomy-tree.js
- app/models/taxonomy.js
- app/templates/components/taxonomy-tree.hbs
carats now only appear when there is a 3rd row of taxonomy
https://trello.com/c/GETV8yQ1/111-preprints-discover-the-caret-does-no-action
> Only display carrots when there are children

- package.json
Update pinned install version of ember-osf dependency to use newest footer changes:
https://github.com/CenterForOpenScience/ember-osf/commit/043c02d1b04fd4e8ca6391887d257e63c12d9560
Trello card:
https://trello.com/c/K0uz5PEg/5-footers-don-t-match
> Update pinned ember-osf version --> footer changes

- app/components/preprint-form-authors.js
Dependent on https://github.com/CenterForOpenScience/ember-osf/pull/129
Needed for reordering contributors https://trello.com/c/Du2ygimQ/108-order-of-authors-on-view-page-not-consistent-with-what-was-saved-and-what-appears-on-project
This passes in reordered contributor list to ember-osf method.  Ember-osf reorderContributors method manually updates indices of contributors in store to match order in passed in contrib list.
> Feature/Pass in reordered contributor list to ember-osf method

- app/components/taxonomy-tree.js
New taxonomy items might have more than 100 children. This, together with the osf PR (https://github.com/CenterForOpenScience/osf.io/pull/6245) will allow us to grab it all.
> Change page size

- app/controllers/index.js
- app/routes/index.js
- app/templates/index.hbs
- config/environment.js
- tests/unit/controllers/index-test.js
https://openscience.atlassian.net/browse/PREP-151
Allow the preprints app to load even when ES is down. On this page, elasticsearch is used specifically for the "x searchable counts" label that appears under the search box.
Also simplify the model hook on the index page, and don't show count box at all when ES doesn't load.
When ES is running:
When ES is down (or inaccessible due to network etc)
> [rfr] Index page should load even if ES is down

- app/controllers/discover.js
- app/styles/app.scss
- app/templates/components/search-result.hbs
JIRA Ticket: https://openscience.atlassian.net/browse/PREP-152
Cleans up the view of links so hyperlinks and information links are displayed separately. 
Bonus: Slight style changes that makes the search result box look much better
- heading font weight changed to normal
- border removed, different box shadow added
> Fix search result links by separating hyperlinks [PREP-152] 

- app/controllers/content.js
- app/templates/content.hbs
Adds social media share buttons to the view preprint page. Matches the behavior and buttons of public projects social media sharing. Uses liquid-fire to animate the toggling of the share row.
> Feature: share preprint on social media

- app/controllers/submit.js
https://openscience.atlassian.net/browse/PREP-90
Allow the `/submit` page "Authors -> search by name" box to search across a variety of name fields instead of just `full_name`.
See description of the multifield contributor search syntax here: https://github.com/CenterForOpenScience/osf.io/pull/6145
In the OSF, go to the settings page (`/settings`). Edit the profile fields so that `full_name`, `given_name`, `middle_names`, and `family_name` all have different values.
Then on the "add a preprint" (`/preprints/submit`) page, search for each of those values in turn. (taking care to search for someone else in between so that it's clear your search is doing something)
In the old search, the user would only show up if you matched the value in the full_name field. Now, a match for any of those …
> [rfr] Contributor search: support filtering on multiple fields

- app/routes/discover.js
https://openscience.atlassian.net/browse/PREP-169
Search page should not save each keyup as query parameter changes into history
Use a standard procedure in Ember (https://guides.emberjs.com/v2.3.0/routing/query-params/#toc_update-url-with-code-replacestate-code-instead) to change the queryparam from pushState to replaceState. 
- Open new browser tab or window
- Start searching for preprints in discover page by adding several keywords and wait for page to load.
- Click the back button of browser or right click to see all previous pages
- Check that individual word entries are not in the history, back button should go to empty discover page or previous pages.
> Change discover page query param from pushstate to replaceState [PREP-169]

- app/routes/404.js
- app/routes/content.js
Use `intermediateTransitionTo` so that the URL stays the same when an invalid URL is accessed.
- Visiting a broken link from an outside source: keeps the URL that you're visiting
- Typing in a broken link: keeps the URL that you're visiting
- Visiting a broken link from **within** the application: reaches an error state from within ember, and updates the window location using a bit of a hacky method.
Visiting a broken link from within the application shows the URL that the link was leading to in the error bar. This is very much not straight forward to accomplish from within ember as most of the URL logic is based on models, and errors are thrown before a "bad" url is ever actually reached.  Maybe with "replaceWith" or "replaceState" - but I had no luck with that yet...
ticket for this …
> For not found use intermediateTransitionTo to keep the URL the same [PREP-154]

- app/index.html
- app/models/preprint.js
- app/templates/404.hbs
- app/templates/application.hbs
- app/templates/components/search-result.hbs
- app/templates/content.hbs
- app/templates/discover.hbs
- app/templates/page-not-found.hbs
- app/templates/submit.hbs
- package.json
https://openscience.atlassian.net/browse/PREP-119
Instead of every page on the site having a title of "OSF | Preprints", allow each page on the site to add its own suffix- eg `OSF Preprints | Search` or `OSF Preprints | This preprint name` .
This will improve usability in the tab bar and back button history. Addon documentation here:
http://tim-evans.github.io/ember-page-title/
(screenshot is outdated; extra separator removed. See above text example)
- Custom page titles
- Unrelated, but: Make date field names consistent with the capitalization used on the node model (and ember conventions)
> [rfr] Custom titles for each page of site

- app/templates/submit.hbs
https://openscience.atlassian.net/browse/PREP-176
Fixes issue where in narrow screens the layout of the tags caused it to be covered up by other divs rendering tags unusable. 
Added clearfix to containing div to account for left alignment of the tags widget.
> Fix tag widget layout in narrow screens [PREP-176]

- app/components/confirm-share-preprint.js
- app/templates/components/confirm-share-preprint.hbs
Share button can be clicked multiple times which could result in a 405 "Could not save preprint; please try again later."
Disables 'Share' button on Add Preprint page after it's been clicked.
> [Hotfix] Prevents Multiclicking of Share Button

- app/templates/components/taxonomy-top-list.hbs
https://openscience.atlassian.net/browse/PREP-172
Improve tooltips by adding size; which takes care of tooltips getting out of the viewport problem for education and also other items. 
- add hint--large class to designate size to taxonomy
- added bonus: add xs sizing so that taxonomy objects appear with correct width at smallest window widths.
> Fix education tooltip by adding size to tooltip [PREP-172]

- app/controllers/discover.js
When pasting a link something like `subject=` gets converted to `subject`, which Ember reads as a value of ` true ` to the Subject query param. When trying to convert query params to filters, it is read as string ` true `. This prevents that behavior (but it does not validate the value of the query param if something is actually passed).
If a queryParam's value is ` true`, do not use it as a filter.
> Make sure filters actually have a value

- package.json
Links work done in https://github.com/CenterForOpenScience/ember-preprints/pull/141 to latest ember-osf version.
> Feature/Pin to Corresponding Ember-OSF Commit

- app/components/confirm-share-preprint.js
- app/components/file-uploader.js
- app/controllers/submit.js
- app/locales/en/translations.js
- app/routes/submit.js
- app/templates/components/file-uploader.hbs
- app/templates/components/preprint-form-header.hbs
- app/templates/components/preprint-form-project-select.hbs
- app/templates/submit.hbs
https://openscience.atlassian.net/browse/PREP-142, https://openscience.atlassian.net/browse/PREP-200
Language changes and fixes for issues found by QA for Existing OSF Project Workflow
- Language changes
- Fix "Are you sure you want to abandon this preprint" to be raised when navigating away from page when file has been set (either file uploaded or existing file selected).
- Allow abstract to be saved when advancing to next section, not just when 'Save and continue' is clicked.
- If user tries to share preprint, and it fails, reenable share button so they can try again.
> Feature/Changes for Existing OSF Project Workflow [PREP-142] [PREP-200]

- app/styles/app.scss
- app/templates/components/convert-or-copy-project.hbs
- app/templates/components/preprint-form-project-select.hbs
- app/templates/submit.hbs
- bower.json
- ember-cli-build.js
##Ticket
https://openscience.atlassian.net/browse/PREP-203
Polish for minor UI and design considerations for the OSF workflow. 
Mainly layout changes affecting spacing, layout and narrow views 
Individual things changed: 
- Selecting an existing project has a placeholder to tell people what that dropdown is for
- Existing project shows a loader that is different than the existing one
- Texts on buttons wrap when needed on the initial upload step buttons and confirmation of are you sure you want to edit existing component buttons
- Borders and paddings are improved
- Buttons should properly collapse in narrow views (<768) 
- Authors table has more space (more of the remove button is visible) but full changes will need to be made in another PR to authors only
- Toggle buttons for upload vs …
> Fix/workflow ui [PREP-203]

- app/components/preprint-form-authors.js
- app/templates/submit.hbs
- package.json
❗ Blocked by https://github.com/CenterForOpenScience/ember-osf/pull/139
There is a feature in Ember preprints that allows you to add contributors from the parent project if a component will contain your preprint. Currently, contributors are added in sequence.  If you have ten contributors on your parent project, any contributors that are not already on component will be added. So nine contributors, nine sequential requests.
This is working locally, but @mfraezz suggested there may be some concurrency issues, so we should attempt to 1) bulk add or 2) wait between requests.  
Send adding parent contributors to component as a bulk request.
Will need to update package.json with new ember-osf commit once corresponding ember-osf PR is merged.
> Feature/Bulk Add Parent Project Contributors [PREP-142]

- app/components/file-uploader.js
Issue found by Allison.  Small issue: if a user selects "Connect to existing project" and then "Upload preprint," and then accidentally uploads a file that is already on the project, they will get an error message when attempting to "Save and continue" letting them know that the file already exists. If they then upload a new file and try to continue on, the "Save and continue" button remains grayed out and unclickable. It seems the upload box needs to be "refreshed" before the button is clickable again. This can be achieved by toggling to "Choose from existing file" then back to "Upload" in the Choose File section, but the "Save and continue" button should be clickable as soon as the new file is uploaded (and all other sections filled out correctly).
Resets state properly when …
> Feature/More Changes to Existing Workflow [PREP-142]

- app/components/preprint-form-authors.js
- app/controllers/submit.js
- app/templates/submit.hbs
Not all contributors were being added from parentProject.  Fetching contributors from parentProject was relying on contributors already in store, fetched by `parentNode.get('contributors')`, instead of a clean loadAll parent node contributors.
Changes the way parent contributors are loaded.
> Feature/QA fix, Importing Existing Contributors

- app/locales/en/translations.js
- app/templates/components/supplementary-file-browser.hbs
- app/templates/content.hbs
- tests/integration/components/supplementary-file-browser-test.js
Needed for https://openscience.atlassian.net/browse/PREP-144
The version of the primary file for the preprint needs to be exposed in the view preprint page.
Adds version of the selected file and a download link for the selected file to the view preprint page.  Download preprint button just downloads primary file.
> Feature/expose primary file version [PREP-144]

- app/routes/content.js
Changes the replacestate url to be absolute, not relative; because replacestate will tack on the url if it's relative.
> Make preprints url replacement absolute url [PREP-194]

- app/controllers/discover.js
- app/utils/elastic-query.js
- tests/unit/utils/elastic-query-test.js
https://openscience.atlassian.net/browse/PREP-160
Fix an issue where certain characters with special meaning in elasticsearch were causing search page to hang. Reported multiple times on sentry post-announcement.
The root cause is that these characters could not be parsed in a query body according to this list:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters
Essentially: ES is returning a 200 response code, and informing the user of the failed query in the payload response. This means that the search page was hanging on a failed query.
Go to `/discover`. Search for something with a quotation mark: `anteaters united"`. Before the fix, there should be errors in the JS console, and the spinner should be stuck on loading. …
> [rfr] [as-is] Fix search page hanging when special characters present in query [PREP-160]

- app/templates/components/supplementary-file-browser.hbs
- app/templates/content.hbs
- tests/integration/components/supplementary-file-browser-test.js
Fix for https://openscience.atlassian.net/browse/PREP-144
Errors pointed out by Todd.
- Download button at the top says 'Download preprint'. 
- Download counts at top reflect primary file downloads, instead of selected file
- Download links at bottom say 'Download preprint' if primary file. 'Download file' otherwise
> Feature/Version Changes [PREP-144]

- app/templates/application.hbs
- ember-cli-build.js
This is no longer needed since we're handling it via [ember-metrics](/poteto/ember-metrics/blob/master/addon/metrics-adapters/google-analytics.js#L32). The duplicate script overrides the GA script from ember-metrics and shows the ID as undefined.
> Remove Google Analytics inline content injection during production build

- app/components/file-uploader.js
- app/controllers/submit.js
The basicsAbstract field is the pending abstract for your preprint.  When you select an existing node to connect to your preprint, the basicsAbstract field is populated with the description stored on the node.  In the node dropdown, if you selected one node, and then changed your mind and selected another, the basicsAbstract field was showing up as the abstract from the first node and not the current node.
When creating a preprint using an existing node, ensures that the basicsAbstract field is equal to the abstract on that existing node.
> [Hotfix] basicsAbstract Field Not Resetting

- app/controllers/resource-deleted.js
- app/locales/en/translations.js
- app/router.js
- app/routes/content.js
- app/routes/resource-deleted.js
- app/styles/app.scss
- app/templates/resource-deleted.hbs
- tests/unit/controllers/resource-deleted-test.js
- tests/unit/routes/resource-deleted-test.js
https://openscience.atlassian.net/browse/PREP-260
If you delete a node that contains a preprint, when you try to navigate to that preprint it will get stuck in an infinite loop.
- Adds resource-deleted route (with GA tracking and branding-specific)
- Redirects to resource-deleted route if the request to fetch the node returns a 410 Gone (actually checking error message details, can't get the status code Ember-side)
- Does not modify url in location bar when redirects - want to see which url had error
> Feature/Redirect to Resource Deleted if 410 [PREP-260]

- app/styles/brands/psyarxiv.scss
https://openscience.atlassian.net/browse/PREP-265
> Style update for PsyArXiv again [PREP-265]

- app/styles/brands/psyarxiv.scss
Only in the footer for PsyArXiv (content page icons have already been changed).
https://openscience.atlassian.net/browse/PREP-267
> Change PsyArXiv social icons to watermelon in footer [PREP-267]

- app/components/file-uploader.js
- app/components/preprint-form-body.js
- app/controllers/content.js
- app/controllers/submit.js
- app/locales/en/translations.js
- app/mixins/setup-submit-controller.js
- app/templates/components/preprint-form-header.hbs
- app/templates/components/preprint-form-project-select.hbs
- app/templates/content.hbs
- app/templates/submit.hbs
Add the ability to display, modify and add licenses to a preprint, taking in the provider's default and subset of available licenses
Addition of license widget on the edit/add preprint flows, and a show license field on the Preprint view page
https://github.com/CenterForOpenScience/ember-osf/pull/152
https://openscience.atlassian.net/browse/PREP-235
For right now, the discard changes and save indicator are behaving weirdly. Fixing it ASAP
> Add license-picker to the preprints add/edit. [PREP-235]

- app/templates/submit.hbs
- package.json
Make the form clearer by moving the apply license yes/no closer to the license widget
> [PREP-274] Move apply license to be next to license widget

- app/controllers/content.js
- app/routes/provider.js
Make provider names case insensitive (redirects to correct location if it is the correct provider name, but wrong case)
Also, get rid of duplicate trackEvent for sharing link buttons on the content page (Google Analytics).
https://openscience.atlassian.net/browse/PREP-286
> Add redirect for urls with uppercase chars, remove duplicate metrics [PREP-286]

- app/components/search-result.js
Problem
---------
On branded preprint search, clicking on the title of a preprint that's got an article DOI directs the user to the DOI. It should send the user to the branded view of the preprint. 
An example is on PsyArXiv - search for "go/no go association task"
This particular example is ALSO broken because the DOI seems invalid- that's unrelated.
Changes
--------
Link to ticket
--------------
https://openscience.atlassian.net/browse/PREP-280
> [PREP-280] Use osf regex if not an outside provider

- app/components/supplementary-file-browser.js
- app/templates/components/supplementary-file-browser.hbs
https://openscience.atlassian.net/browse/PREP-241
If preprint file is stored inside a folder under OSF storage, it does not load.  Currently, the only files that are displaying are top level files.
1) Makes a separate request to load the preprint file from the preprint relationship instead of searching through the top-level files for a match.  
2) When clicking on a folder, links to the OSF node files page.  Currently, the page links back to itself.
The hierarchy in the UI will not be correct when the preprint is stored inside a file, but I think this is fine, esp because this file gets a special 'Primary' indication, showing that it's different than the others.  I am showing this preprint file alongside all the top-level files and folders, even if that preprint file is actually stored …
> Feature/Preprint File inside Folder [PREP-241]

- app/locales/en/translations.js
Reference "projects" instead of "nodes" when user has no valid nodes that can be converted into a preprint.
None
https://openscience.atlassian.net/browse/PREP-270
> Feature/User Message "Projects" instead of "Nodes" [PREP-270]

- package.json
Change to latest Ember-OSF Version.
Upgrades version in package.json to work with https://github.com/CenterForOpenScience/ember-osf/pull/163
Project dropdown should now load all the projects instead of just the first ten.
> Hotfix/Bump Ember-OSF Version

- app/components/preprint-form-project-select.js
- app/templates/components/preprint-form-project-select.hbs
https://openscience.atlassian.net/browse/PREP-254
❗️ Depends on https://github.com/CenterForOpenScience/ember-osf/pull/148
Searching for a project title to add a preprint to should also return all components under that project in the results.
Pass a custom matcher into the power-select component that looks through the root title, node title, and parent title for a match, instead of just the node title.
> Feature/Project Dropdown Filter both Projects and Components [PREP-254]

- app/helpers/get-ancestor-descriptor.js
- tests/unit/helpers/get-ancestor-descriptor-test.js
https://openscience.atlassian.net/browse/PREP-257
❗️ Requires that https://github.com/CenterForOpenScience/ember-osf/pull/148 is merged.
On the `Add Preprint` page, you have the option to connect your preprint to an existing project.   The `get-ancestor-descriptor` helper allows us to format the projects in the project dropdown similarly to how they are formatted in the dashboard, with a hierarchy, so users can distinguish between similarly-named projects.  However, there are some errors in the logic, particularly when a project in the hierarchy is private.
- Rewrites get-ancestor-descriptor so logic is easier to follow.
- If parentId, rootId, parentparentId's are undefined  (case if private or does not exist), attempts to pull id from relationship link (in which case it is private). If …
> Feature/Rewrite get-ancestor-descriptor helper [PREP-257]

- app/components/taxonomy-top-list.js
Tooltip for engineering subdisciplines on preprints content page has too many subdisciplines.
Changes subdisciplines for the tooltip to:
Biomedical Engineering and Bioengineering
Chemical Engineering
Civil and Environmental Engineering
Electrical and Computer Engineering
Mechanical Engineering
https://openscience.atlassian.net/browse/PREP-275
> Feature/Engineering Tooltip Subdisciplines [PREP-275]

- app/styles/brands/_brand.scss
OSF Preprints and Branded Preprint Headers share same top padding of 150px.  OSF preprints has two navbars, an OSF navbar and a preprints navbar, while branded has one navbar.  The padding on branded index pages seems large.
Reduces top padding on branded preprint header by 50px, which is the height of the navbar.
Before
After
https://openscience.atlassian.net/browse/PREP-283
> Feature/Branded Preprint Header Padding [PREP-283]

- app/styles/app.scss
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-393
1 ) Move citations to last on the right side display; user entered metadata should come before the static citation content. 
2) Bold the headings to make more readable. 
3) Get rid of horizontal scroll bar (that appears when docking machine)..Removed liquid-spacer. This doesn't seem to be needed anymore.
> Fix/Citations Placement and Headings on Content Page [EOSF-393]

- app/helpers/get-ancestor-descriptor.js
https://openscience.atlassian.net/browse/EOSF-395
Brought up by QA: It looks like if you are admin on a nested component (level 3), but not a contributor on the parent or component (levels 1 and 2), the project appears as "Private / ... / Private / 3" which implies there is another project between 1 and 2, even though there is not.
If both the parent and root are private there is no way to deduce how many levels there are. I was giving it the default four levels since I didn't know, the dashboard gives it default three, but there's no way to tell. The API doesn't return a lot of info if items are private.
**If number of levels can't be deduced because of private projects in the hierarchy, change to this: `... / node title`**
> Feature/Get-Ancestor-Descriptor Improvement [EOSF-395]

- app/controllers/content.js
- app/styles/app.scss
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-435
Allow citations and other non-abstract pieces of the view preprint page to be seen right away.
Add "see more" to the abstract that expands it if it is too long.
> [EOSF-435] Add "see more" for long abstracts on view preprint page.

- app/locales/en/translations.js
- app/templates/submit.hbs
https://openscience.atlassian.net/browse/EOSF-474
Include language in Preprints submit that indicates a user should have permission to post their preprint.
> [EOSF-474] Add more details to the preprint submission language

- app/styles/brands/scielo.scss
- app/templates/index.hbs
https://openscience.atlassian.net/browse/EOSF-238
Fix bug on scielo, changing color to black to fix a lot of visibility issues, and only have the advisory container if the current provider actually has an advisory board.
> [EOSF-238] Change scielo text to black and only have board container if it exists

- app/components/provider-carousel.js
- app/styles/app.scss
- app/templates/components/provider-carousel.hbs
- app/templates/discover.hbs
- app/templates/index.hbs
- tests/integration/components/provider-carousel-test.js
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-499
Add a scrolling list to the Preprint Services banner to allow the overflow of many preprint server logos to be easily and manually viewed by curious users.
We should show 5 logos and provide tooltips for what the logo is referencing.
This will replace the current logos.
Added provider-carousel component to be used on both the Index and Discover Pages.   Properties are preprint-providers and lightLogo argument. If true, will display light logos and appropriate links for index page, if false, will display dark logos and links for discover page.  More customization of component would be needed if used elsewhere in the application.
Added listener for screen resize so the number of providers per slide on an xs screen is one.  >xs screen, num …
> Feature/Preprint Provider Carousel [EOSF-499]

- app/controllers/discover.js
https://openscience.atlassian.net/browse/EOSF-514
Updates the discover route so that Preprint Providers in from the API are used in the whitelist (not hardcoded)
/preprints/discover (OSF Preprints only) should now have all of the providers available. Providers in the API, but not in SHARE will be displayed with with a document count of 0.
Providers should now load automatically when added to the API
> [hotfix] [EOSF-514] Use providers list from APIv2 instead of hardcoded list

- app/templates/components/preprint-form-authors.hbs
https://openscience.atlassian.net/browse/EOSF-503
If a user is in the Create a Preprint flow and clicks on a contributors name, the user is taken to the user's profile page. If the user hits the back button, s/he is returned to the create a preprint flow but at the beginning of the process. There is no way for the user to return to the draft state or complete the preprint. This creates a poor user experience.
We should open the contributor profile in a new tab to prevent this.
Open contributor links in a new tab on Submit page.  This includes links in search results as well as links for current contributors.  Also applies in mobile view.
> Feature/Submit Page Contributors New Tab [EOSF-503]

- app/styles/app.scss
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-462
We should not be linking to unregistered contributor profile pages.  
FIx this on the content page so there is no link if user hasn't confirmed their account.
> Feature/Unregistered Contributors on Content Page [EOSF-462]

- app/templates/components/confirm-share-preprint.hbs
https://openscience.atlassian.net/browse/EOSF-478 
The preprint app has a modal to confirm sharing of new preprints. 
Pressing enter is needed to confirm share action presented in a modal.
Used autofocus attribute, a boolean attribute, to specify that the button should automatically get focus when the modal loads.
> Using enter button to confirm the share action in modal [EOSF-478]

- app/components/provider-carousel.js
- app/templates/components/provider-carousel.hbs
- tests/integration/components/provider-carousel-test.js
https://openscience.atlassian.net/browse/EOSF-505
From ticket:
The logo carousel on the preprints landing page and discover page can display up to 5 logos before it needs carets to scroll to see more. The non-functional carets should be removed when there are fewer than 6 logos.
It would also be ideal if the logos could be centered, perhaps just making the number of columns equal to the number of items if it's less than five. Just make sure they don't get too tall or anything crazy.
If five or less providers:
- Remove carets
- Center logos (by adding a dynamic column offset)
> Hotfix/Provider Carousel <5 Providers [EOSF-505]

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-525
Update preprints to use newest ember-osf
User facing: Updates the destination of the navbar "/registries" link
Internal: Updates ember-osf to 0.2.1 (and update yarn.lock accordingly) 
None expected. Merging yarn.lock back to develop might be messy.
> [hotfix] Update to use ember-osf 0.2.1

- app/routes/content.js
https://openscience.atlassian.net/browse/EOSF-526 
Unable to Render Preprints without licenses.
This was caused by trying to retrieve the name attribute from the license, which in this case equals to null. Added a check to handle the null value.
Noticed that for preprints in this case, once loaded, the dataPublished is equal to null too, causing a warning with the moment-format helper.  Added another check to handle this situation.
> Render Preprints without licenses [EOSF-526]

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-538
Use ember-osf 0.3.0, newly released to the NPM registry.
Update package.json and yarn.lock to use newest ember-osf version.
I was not able to run this locally at the moment, due to my docker images being out of date. In the interests of time, I request that the reviewer verify code runs in principle before merging.
> Update to use ember-osf 0.3.0 [#EOSF-538]

- app/routes/content.js
https://openscience.atlassian.net/browse/EOSF-552
Needed for Google Scholar to index preprints
Changes the `property` attribute to `name` on non-open graph meta tags on the content route
N/A
> [Hotfix] [EOSF-552] update meta tags for Google Scholar

- app/controllers/discover.js
- app/routes/discover.js
https://openscience.atlassian.net/browse/EOSF-494 
This is a follow-up to EOSF-426, which clears selected filters when navigating away from the preprints search page. However, it does NOT clear text entered into the search box. 
This ticket is to clear the text entered in the search box.
- Defined a new method within the controller to clear the search box.
- Call the new method from the existing willTransition method inside discover.js
> Clear search box text when navigating away from page [EOSF-494]

- app/mixins/analytics.js
https://openscience.atlassian.net/browse/EOSF-523
Mouse events (e.g. Cmd+click) leading to invalid redirects (404s)
Check url type before redirecting on click google analytics event
> [EOSF-523] Check url type before redirecting on click google analytics event

- app/templates/components/search-result.hbs
https://openscience.atlassian.net/browse/EOSF-529
SHARE isn't able to get a timestamp from most providers, which means that some of the timestamps in Ember Preprints and Registries are randomly assigned.  The purpose of this ticket is to remove the time portion of the timestamp from Preprints.
Changes for this ticket include changing the format of the timestamp to only be in "YYYY-MM-DD" format, leaving out the time.
Originally, the 'Added on' date for Preprints would show the time in addition to the date.
<br>
After the changes, the 'Added on' date now only shows the date without the time.
> [EOSF-529] Hide random hour of the day timestamp on Preprints

- app/styles/app.scss
https://openscience.atlassian.net/browse/EOSF-508
On mobile, the carets on the preprints provider carousel are very small.  This ticket fixes the size issue on mobile devices.
All changes were done in CSS to increase the size of the carets and change the top margin to fit the new size.
> [EOSF-508] Increase caret(s) size for preprint provider carousel

- app/styles/app.scss
- app/templates/components/supplementary-file-browser.hbs
https://openscience.atlassian.net/browse/EOSF-531
Content on the preprints content view overflows into the citations section when the browser window width is between 990px and 1200px.
Updates the bootstrap classes and stylesheet
N/A
> [EOSF-531] Fix overlap on content view

- app/controllers/content.js
- app/locales/en/translations.js
- app/styles/app.scss
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-555
Needed for Google Scholar to index the page properly
* Sets `expandedAbstract` to true by default if the user agent contains `Prerender` (per the [Prerender docs](https://prerender.io/documentation/faq))
* Simplifies the description property
* Use CSS for the ellipses
* Move strings to translation file
* Hides the show more/show less button if the the description the shortened description is less than 350 characters
N/A
> [Hotfix] [EOSF-555] Prerender full abstract

- app/controllers/content.js
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-555
Last fix broke short abstracts
Introduced in #300
This accounts for short abstracts
> [Hotfix] [EOSF-555] Abstract Truncation take 2 🎬

- app/styles/app.scss
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-501
The download count for a preprint was breaking to the next line before the share icons.  This ticket fixes this issue.
Added a new class to both containers in order to remove the original template styling for the width of each container.
<b>BEFORE</b>
Before changes, the download count would wrap to the next line before the icons next to it.  This could be confusing to users who expect to see the number of downloads next to the label.
<hr>
<b>AFTER</b><br>
After changes, the download count remains on the same line as the rest of the text. 
When the screen becomes too small to fit everything on one line, the icons are the first to move to the next line underneath the "Download preprint" button.
Because CSS can potentially act differently …
> [EOSF-501] Improve Preprint download count wrapping

- app/controllers/discover.js
- app/locales/en/translations.js
- app/templates/components/search-result.hbs
https://openscience.atlassian.net/browse/EOSF-438
The "Date Added" dates are the dates the Preprint was created. The Sorting date, however, is really the Date Modified date. There should be consistency to meet user expectations.
- Update the translation file. 
- Use the translation service.
- Rename sort buttons to "Sort by Modified Date (newest to oldest)" and "Sort by Modified Date (oldest to newest)"
- Update the "Added on" field to be "Last edited on"
> Update the language for "sort by options" and "added on" field [EOSF-438]

- app/controllers/discover.js
- app/styles/app.scss
- app/templates/discover.hbs
https://openscience.atlassian.net/browse/EOSF-528
The order of sorting in Preprints would change based on what the user selects.  The order of the list should stay consistent regardless of what is selected.  
The list of available sources a user can choose from is static and doesn't change regardless of what's chosen.  
The main style aspect that was changed was to make the font of the dropdown better match the style of other dropdowns on the site (mainly the navbar).  The alignment of the dropdown list was changed to be anchored on the right to match its position on the page.  When you hover over the choices, the background of the list element changes to a slightly lighter color, and the font gets a bit darker.
And when you select something from the list, the order of the list will stay …
> [EOSF-528] Fixed order on Preprints Search sort

- config/environment.js
https://openscience.atlassian.net/browse/EOSF-581
Sometimes in Ember-OSF, we need to know the consuming application - to handle things differently for preprints or registries.
A new entry appName is added to /config/envirnoment.js , this entry will be used to hold the app name. The new mixin in ember-osf will have an attribute the read this entry and used by the consuming component.
> Detecting Consuming Application in Ember-OSF (preprints) [EOSF-581]

- package.json
- yarn.lock
Probably this is not better than using a commit hash because we have to generate a new yarn lock each time anyways (and this might be worse depending). We can change it to a commit hash next time rather than using `#develop` if we hate this.
> Use develop branch for ember-osf until ember-osf 0.4.0 is released

- app/routes/content/index.js
https://openscience.atlassian.net/browse/EOSF- 
Google Scholar needs citation_pdf_url for all the things, but we only supplied it for actual PDFs.
This uses the MFR URL from the primary file, *should* render a PDF.
> [hotfix] Google Scholar citation_pdf_url

- app/styles/_variables.scss
- app/styles/app.scss
https://openscience.atlassian.net/browse/EOSF-636
Fix provider carousel controls overlapping provider logos.
* Import SASS variables before bootstrap so that bootstrap variables can be overridden
* Override bootstrap carousel control width (set to 10%, was 15%)
This fix is global to preprints so it also fixes the carousel on /preprints/discover
> [EOSF-636] Provider carousel controls fix

- app/styles/brands/agrixiv.scss
- app/styles/brands/bitss.scss
https://openscience.atlassian.net/browse/EOSF-613
When navbar links have focus state for BITSS and AgriXiv preprint providers, the link color is the same as the surrounding background color.
Modifies theme-color-5 for agrixiv and bitss.
> Feature/BITSS and AgriXiv Navbar Link Fixes [EOSF-613]

- app/controllers/discover.js
https://openscience.atlassian.net/browse/EOSF-608
Prevent inconsistent behavior of window location on change of search result page. As indicated by the ticket, depending on the browser being used, going to another page of search results either moves the window to the middle of the results or stays at the bottom. The wanted behavior is to have the window be relocated to the top of the search results, like our other search pages. 
Add a window.scrollTo on the page change action. The value is calculated based on the location of search results, to allow for proper scrolling even when the page is at half size. Alternatives to how the value should be calculated are welcome, as this does not seem to be the most robust way to do it, although it does the trick here consistently and smoothly.
> [EOSF-608] Add scrollTo on page change of search results

- app/components/subject-picker/template.hbs
- app/locales/en/translations.js
- app/styles/app.scss
- https://openscience.atlassian.net/browse/EOSF-285
When creating a preprint, disciplines and sub-disciplines would smash together when the screen became too small to fit on one line.  This will fix the styling of the disciplines and sub-disciplines when they break onto new lines.
- Changed HTML to add another container around each listed item and changed the styling to match. 
- Moved 'x' icon to be within the new div containers.
- None expected
- When a user adds a new sub-discipline to the list, all listed items already selected will have an arrow at the end unless they are the last item in the list.
- In the case that the screen size is too small to fit all items in the list on one line, they will break up and move to the next line in order to fit.
- If the screen is too small to fit …
> [EOSF-285] Styling for Selected Sub-disciplines List

- app/styles/brands/psyarxiv.scss
https://openscience.atlassian.net/browse/EOSF-620 
Recently, PsyArXiv changed their colors from #ff383f to #CF1D35.
The buttons and logo colors were changed, but the footer did not get updated to their new color.
Update the footer color to #CF1D35 in psyarxiv.scss
> Update PsyArXiv branded footer color [EOSF-620] 

- app/components/subject-picker/template.hbs
- app/styles/app.scss
To fix the alignment for the subject taxonomies.
The ` inline-block ` style was throwing the subject class off.  Changes include removing that styling from the ` .subject ` class and tweaking styling for other containers that used that property of the ` .subject ` class.
After changes, the subject taxonomies look like they did before previous changes to the class.
The subject-picker, which used the ` inline-block ` style of the ` .subject ` class, also looks like it was designed to before changes.
https://openscience.atlassian.net/browse/EOSF-285
> Fix alignment for subject taxonomies [EOSF-285]

- app/controllers/discover.js
https://openscience.atlassian.net/browse/EOSF-635
Now that Preprints.org has been fully backharvested, add Preprints.org to the whitelist of available preprint servers.
> Hotfix/Whitelist Preprints.org [EOSF-635]

- app/templates/components/search-result.hbs
https://openscience.atlassian.net/browse/EOSF-644
Hyperlinks broken on search results.  They don't force open a new tab (or window). User must right-click and open in new tab to see content/page. 
Adds onclick to 'a' tag.
> Feature/Fix Hyperlinks on Search Results [EOSF-644]

- app/components/taxonomy-top-list.js
- app/templates/components/taxonomy-top-list.hbs
- bower.json
https://openscience.atlassian.net/browse/EOSF-656
Remove tooltips on launch page due to conflicts with custom taxonomies.
> [EOSF-656] Remove tooltips from landing page subjects

- app/styles/app.scss
- app/styles/brands/_brand.scss
https://openscience.atlassian.net/browse/EOSF-657
Fix color of branded subjects on submit subject picker
Move CSS around so it can be overwritten by brand, add right-arrow element to branded css
> [EOSF-657] Fix color of branded subjects on submit subject picker

- package.json
N/A
Update to latest pre-0.5.0 ember-osf
Updated commit hash in package.json
Preprints is using the latest ember-osf
> Updated to latest pre-0.5.0 ember-osf

- app/controllers/discover.js
https://openscience.atlassian.net/browse/EOSF-558
Issue found by QA - 
> when navigating to the Discover page, then to landing page and back via the navbar, it adds a duplicate tag under “Active filters.” 
Update the clearFilters method on the discover controller to reset activeFilters > providers to an empty list.  Previously, we were setting to an empty list unless this was a preprint provider, in which case we were retaining the preprint provider under activeFilters.
However, the search-facet-provider component takes care of setting this activeFilter when needed, so it should just be cleared alongside the other activeFilters.
> Feature/Clear Active Filters > Providers [EOSF-558]

- ember-cli-build.js
Allow file paths to behave as if we are pointing to an outside cdn.
Dont add cache busting suffix to preprint assets
> Dont add cache busting suffix to preprint assets

- config/environment.js
N/A
Make providerAssetsURL settable via environment variable.
Changed providerAssetsURL in config/environment.js to be set via PROVIDER_ASSETS_URL environment variable and fall back to staging-cdn if the environment variable is not set.
None.
> Make providerAssetsURL settable via environment variable

- package.json
N/A
Rebuild node-sass after yarn installs it because https://github.com/sass/node-sass/issues/1804
https://github.com/yarnpkg/yarn/issues/1981 discusses the issue on the yarn side and suggests this as a workaround.
Added "npm rebuild node-sass" as a postinstall hook in package.json
Successful builds!
> Add postinstall node-sass rebuild

- .travis.yml
https://openscience.atlassian.net/browse/EOSF-699
Use "sudo: required" in Travis to get a build environment with more memory
Changed to "sudo: required" in .travis.yml
Builds don't fail?
> [EOSF-699] Use sudo:required in Travis

- app/styles/app.scss
https://openscience.atlassian.net/browse/EOSF-675
The disciplines on a preprint detail page used to have boxes around them, but now those are gone. 
Restored subject-preview class definition to stylesheet. Was moved to ember-osf in the discover-page widget PR but was nested under search-results, so was not available to use in this location on the preprints index page.
Screenshots coming - can't authenticate at the moment, so I can't create a preprint locally to view + having docker issues.
> Feature/Restore Subject-Preview Styles [EOSF-675]

- app/templates/application.hbs
https://openscience.atlassian.net/browse/EOSF-702
The url for branded preprints' stylesheets is not correct.  The purpose of this ticket is to change it to point to the right location.
None
Before changes, branded preprints wasn't being given the right css, so the formatting was using some of the basic preprints css instead:
After changes, the branded preprints provider is showing the right styling:
> [EOSF-702] Branded preprints domain not getting enough css

- app/components/additional-provider-list.js
- app/components/search-preprints.js
- app/controllers/discover.js
- app/locales/en/translations.js
- app/routes/submit.js
- app/styles/app.scss
- app/templates/components/additional-provider-list.hbs
- app/templates/components/preprint-navbar-branded.hbs
- app/templates/components/search-preprints.hbs
- app/templates/discover.hbs
- app/templates/index.hbs
- bower.json
- config/environment.js
- ember-cli-build.js
- package.json
- tests/integration/components/additional-provider-list-test.js
- tests/integration/components/search-preprints-test.js
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-680
❗️ depends on https://github.com/CenterForOpenScience/ember-osf/pull/223
❗️ Might need some follow-up changes to the new navbar to conditionally remove the "Add preprint" link on a branded provider.
⭐️ NOTE: additionalProviders array on preprint-provider should have the names of the sources that SHARE is expecting, otherwise we will need some sort of transformation in preprints
⭐️ OSF Provider also needs allowSubmissions populated
Make preprints-side changes to implement ASU repository.  Preprints templates/controllers/routes have been modified themselves to make a collection of multiple types of resources with multiple providers work with the same code as branded preprint-providers.
If additionalProviders exist on the preprint-provider:
- …
> Feature/ASU Repository [EOSF-680]

- app/sanitizers/advisory-board.js
- app/sanitizers/description.js
- app/sanitizers/footer-links.js
- app/templates/components/preprint-footer-branded.hbs
- app/templates/index.hbs
- bower.json
- package.json
- tests/integration/components/preprint-footer-branded-test.js
- tests/unit/helpers/sanitizers-test.js
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-695
These are the template changes to match Casey's preprint model changes. Properties such as twitter, facebook, and instagram links are removed.
Delete references to  email_support, email_contact, social_facebook, social_twitter, and social_instagram in branded_preprint_footer. Instead use footerLinks, description, and advisoryBoard in handlebars templates.
IMPORTANT: The first line of the footers for all current preprint providers will need to be added to the footerLinks field admin app in order for them to show up correctly.
> Feature/update templates to match provider models [EOSF-695]

- app/index.html
- tests/index.html
https://openscience.atlassian.net/browse/EOSF-602
Update to use the latest version of MathJax to ensure there is no dependency on the now defunct MathJax CDN. See: https://github.com/mathjax/MathJax/releases/tag/2.7.1
Changed app/index.html to include MathJax 2.7.1 from cdnjs.
Should be none since [MathJax 2.7](http://docs.mathjax.org/en/latest/whats-new-2.7.html) was primarily just a bugfix release with a few opt-in features.
> Updated to use MathJax 2.7.1

- app/index.html
https://openscience.atlassian.net/browse/EOSF-548
When you clear your cache, font awesome fonts aren't loading on first-load in _Safari_. Subsequent loads are fine.
Add minified Font-Awesome CDN to head tag of index.html.  There might be better ways to do this, but this seems to ensure that the icons are available on first load.
> Feature/Font-Awesome in Safari [EOSF-548]

- config/environment.js
https://openscience.atlassian.net/browse/EOSF-714
Remove footer license language for MindrXiv
Changed value for mindrxiv permissionLanguage to 'no_trademark'
Footer license language is removed for MindrXiv
> [EOSF-714] Remove footer license language for MindrXiv

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-713
Update to latest ember-osf that includes adding emailSupport back to the preprint provider model
Update commit hash for ember-osf in package.json
None
> [EOSF-713] Update to latest ember-osf commit on develop

- app/controllers/discover.js
- app/routes/discover.js
- app/templates/discover.hbs
https://openscience.atlassian.net/browse/EOSF-680
Add preprint button not showing up on discover page for OSF provider only. Cause: OSF provider resource was not being passed to the discover page component, because that provider was excluded from the model hook.
model for discover route => Changed to all providers, instead of providers excluding OSF
externalProviders computed property defined => all providers excluding OSF
externalProviders passed into the discover-page component to populate the provider carousel.  The model is used to get the themeProvider, so the osf provider can be lifted from this and passed to the discover page.  Now the add preprint button will show.
> Feature/Create External Providers Property [EOSF-680]

- app/sanitizers/advisory-board.js
Relates to OSF PR [#7381](https://github.com/CenterForOpenScience/osf.io/pull/7381)
- No ticket.
- Agrixiv uses `h3` tags in their advisory board on production, so we should probably allow that. 
- Edit allowed tags in advisory-board.js
> [feature] Edit Advisory Board Allowed Tags [No Ticket]

- app/sanitizers/advisory-board.js
- app/sanitizers/description.js
- https://github.com/CenterForOpenScience/osf.io/pull/7392
- https://openscience.atlassian.net/browse/OSF-8206
- Allows (minimal) styling of preprint providers advisory_board and description fields.
- Adds `style` to allowed attributes.
- None expected.
> [feature] Allow style attribute in advisory_board and description [OSF-8206]

- app/templates/index.hbs
https://openscience.atlassian.net/browse/EOSF-735
So that the total-share-results component is only used on index page for unbranded preprint providers.
Add a conditional to stop the component from rendering.
> Feature/Remove total-share-results from branded index pages[EOSF-735]

- app/controllers/submit.js
- app/locales/en/translations.js
- app/templates/content/index.hbs
- yarn.lock
**Note: This PR depends on https://github.com/CenterForOpenScience/ember-osf/pull/215
Builds will fail until that PR is merged and this PR updated to use latest ember-osf.**
https://openscience.atlassian.net/browse/EOSF-631
Update Preprints front-end for automatically minted Preprint DOIs
* updated verbiage to reflect automatic minting of DOIs
* added Preprint DOI to preprint content page
None
* The Preprint DOI may not appear immediately after submission because the DOI may still be in the process of being minted. It should appear after a page refresh.
* double-check verbiage changes
* should make sure both user-entered publication DOI and minted DOI are displayed properly and link correctly
> [EOSF-631] Preprint UI updates for new DOIs

- app/routes/content/index.js
https://openscience.atlassian.net/browse/EOSF-764
To add mint DOI's to the meta tags so that Google Scholar can get access to them.
- Added a conditional to check for either the Peer Review DOI's or the mint DOI's for Highwire Press
- Changed Dublin Core DOI to point at mint DOI's
- Added a conditional Dublin Core DOI in the case that there is a Peer Review DOI
In the case that there is a Peer Review DOI, `citation_doi` and `dc.relation` will point to that DOI.
However, if there isn't a Peer Review DOI, then `citation_doi` will point to the mint DOI and `dc.relation` will not exist (since there isn't a peer review DOI)
> [EOSF-764] Add preprint mint DOI's in metatags

- app/templates/components/error-page.hbs
- app/templates/components/preprint-navbar-branded.hbs
https://openscience.atlassian.net/browse/EOSF-621
On the branded preprints 'Page Not Found' page, some of the links aren't rendering properly and are showing `undefined`.
The main changes done for this ticket include changing the `{{ link-to }}`'s into html `<a>` tags.  The code done in this ticket was taken from https://github.com/CenterForOpenScience/ember-preprints/pull/335 and tested to make sure it works.
Previously, the links being shown on the 'Page Not Found' page for branded preprints would show as `undefined`.  
After the fix, the links show the correct branded preprint in the link, and will take you to the right page when clicking on it.
> [EOSF-621] Branded preprints links on 'Page Not Found'

- package.json
N/A
The purpose of this script is to update ember-osf to use the latest commit from the develop branch. It can be run with `yarn use-ember-osf-develop`. The git url in package.json will be tagged with a timestamp, which forces re-resolution of develop to the latest commit on subsequent updates and indicates when ember-osf was last updated to the tip of develop. The resolved url in yarn.lock points to the actual commit.
Added a script to update ember-osf to use the latest commit from the develop branch.
None
> Added npm script to use ember-osf at the tip of the develop branch

- app/components/search-facet-taxonomy.js
- app/templates/components/search-facet-taxonomy.hbs
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-753
Update discover page to work with custom taxonomies
* Use latest ember-osf to get shareTitle in taxonomy model (see https://github.com/CenterForOpenScience/ember-osf/pull/241)
* Use full SHARE taxonomy strings for subjects filter
Make sure selecting one or more subject filters works properly.
> [EOSF 753] update discover page to work with custom taxonomies

- app/routes/content/index.js
https://openscience.atlassian.net/browse/EOSF-764
To fix issues with the preprint DOI meta tags.  
Changed the conditionals to catch both 'null' and '' to determine whether or not to display the DOI tags.
> [EOSF-764] Preprint DOI tags

- app/templates/components/taxonomy-top-list.hbs
https://openscience.atlassian.net/browse/EOSF-788
Update links for subjects on landing page to work for custom taxonomies.
Prepend subjects with shareTitle
Make sure this works properly for unbranded and branded preprints
> [EOSF-788] Prepend subjects with shareTitle for hilighted taxonomies links

- app/routes/index.js
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-691
Show highlighted instead of top level taxonomies on index page.
* use latest ember-osf to be able to access highlighted taxonomies from preprint provider
* query highlighted taxonomies instead of taxonomies with no parent
* make sure highlighted child subjects appear and non-highlighted top-level subjects don't
* make sure all top level subjects appear when a provider has no highlighted taxonomies
> [EOSF-691] show highlighted taxonomies

- app/templates/components/taxonomy-top-list.hbs
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-691
Use path for highlighted taxonomies link so that we have the full hierarchy
Use subject.path in highlighted taxonomies link
Make sure clicking on highlighted taxonomies that are children results in proper filter on discover page
> [EOSF-691] use path for highlighted taxonomies

- app/templates/application.hbs
To remove the donate banner from branded preprints.
Add a conditional to check if the preprint provider is branded.
> [EOSF-778] Remove donate banner from branded preprints

- app/templates/application.hbs
- app/templates/index.hbs
The banner should not show up except on landing pages.
Remove the donate banner from the main application page and move it to the landing page.
> [EOSF-778] Remove banner except on preprints landing page

- app/routes/content/index.js
[OSF-8265](https://openscience.atlassian.net/browse/OSF-8265)
Enable osf preprints metatags to be picked up by Zotero Connector (browser extension)
Problem statement is well documented [here](https://forums.zotero.org/discussion/comment/279664)
Fires event trigger that forces zotero picker to refresh/parse anew after normal
hooks are done.
> [Feature] Add zotero update event trigger [OSF-8265]

- app/services/theme.js
- app/templates/application.hbs
- app/templates/components/preprint-navbar-branded.hbs
- package.json
https://openscience.atlassian.net/browse/EOSF-655 
Hide "Theses" from page title and nav bar for Thesis Commons
* add property to theme service for determining if the preprint word should be included in the title
* use this property to determine when to include the preprint word in the:
* page title
* nav bar
N/A
> Hotfix/0.111.15 [EOSF-655]

- app/components/search-facet-provider.js
- app/templates/components/search-facet-provider.hbs
- package.json
https://openscience.atlassian.net/browse/EOSF-814
"Other Preprint Repositories" should always link to the OSF domain, even when on a branded domain.
Use OSF.url in the link.
Should do the right thing in all environments.
> Hotfix/0.111.16 [EOSF-814]

- app/components/search-facet-provider.js
https://openscience.atlassian.net/browse/EOSF-766
To fix the provider filter for branded preprints.
The provider filter is determined by comparing the id to the title of the provider.  This does not work with some providers (ex. lissa != LIS Scholarship Archive).  The change in this fix is to compare the title given by SHARE to the title of the provider.
> [EOSF-766] Fix provider filter on branded preprints

- .nvmrc
- .travis.yml
- Dockerfile
- package.json
❗️Needs CenterForOpenScience/osf.io#7350
https://openscience.atlassian.net/browse/EOSF-554
Updates Node.js version to 8
Remove lts/boron and replace it with 8 everywhere, and add --ignore-engines due to  qunitjs/qunit#1184.
This should not affect any functionality, normal regression only.
> [EOSF-554] Update to Node.js version 8

- app/index.html
- ember-cli-build.js
No ticket
Needed for single docker builds, rely on replaceable meta tag content.
Removes inline js code from ember-cli-build and puts static js in index.html, which relies on the ember config from the meta tag.
N/A
Make sure it still works with branded domains, but it should be fine. Just changing the source of the config, not how it works.
> Get ember config from meta tag

- app/helpers/branded-preprint-url.js
- app/templates/components/provider-carousel.hbs
https://openscience.atlassian.net/browse/EOSF-773
When a provider has a domain and has domain_redirect_enabled set to true, it should link to it's domain instead of use an osf.io url.
Added a conditional to check the domain and redirect settings for providers in the carousel.
To test this, be sure to have a provider with both a domain and domain_redirect_enabled set to true.  The final result should look like this on preprints:
> [EOSF-773] Provider carousel link to domain with redirect enabled

- app/components/search-facet-provider.js
- app/controllers/discover.js
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-667
Add `thesis` as a possible SHARE publication type to be used for filtering on the discover page.
- Add `thesis` as one of the publication types to be filtered
- Add `thesis` to the search-facet to return results for providers that have theses
> [EOSF-667] Add 'thesis' as possible SHARE publication type

- app/components/search-facet-provider.js
https://openscience.atlassian.net/browse/EOSF-782
To remove ASU as a possible provider to filter results by on the discover page.
Add a filter when returning results to specifically filter out ASU.
The change is just to filter out ASU, so the only thing you'll really need to check is whether or not it shows up in the list.
> [EOSF-782] Filter out ASU for search facet providers

- app/router.js
- app/routes/application.js
https://openscience.atlassian.net/browse/EOSF-819
Make sure the theme id is set to the provider that matches the branded domain before looking up highlighted taxonomies.
Moved branded domain lookup to application route's beforeModel hook.
When a branded domain is detected, routing will pause until the API query returns the provider for the domain.
Unable to replicate the issue on staging (only seen on production) but just make sure branded domains still work properly.
> [EOSF-819] Move branded domain lookup to application route's beforeModel hook

- app/styles/app.scss
https://openscience.atlassian.net/browse/EOSF-818
Hide overflow and use ellipsis for long highlighted taxonomy names.
Added `overflow: hidden` and `text-overflow: ellipsis` to style for highlighted taxonomies
None
> [EOSF-818] Hide overflow and use ellipsis for long highlighted taxonomies

- app/services/theme.js
- app/styles/app.scss
- app/templates/components/preprint-footer-branded.hbs
- config/environment.js
- tests/unit/services/theme-test.js
https://openscience.atlassian.net/browse/EOSF-820
Remove arXiv trademark license permission language
Removed arXiv trademark license permission language
arXiv trademark license permission language will no longer appear in the footer for branded preprints (unless it is added to footer_links, and then it will appear above the copyright notice).
> [EOSF-820] Remove arXiv license permission language

- app/routes/application.js
https://openscience.atlassian.net/browse/EOSF-833
Fix authentication for preprints
Call parent's beforeModel() in application route
Authentication should work properly again
> [EOSF-833] Call parent's beforeModel() in application route

- app/routes/provider.js
- config/environment.js
https://openscience.atlassian.net/browse/EOSF-827
Check provider route slug against API
Check provider route slug against API
Branded provider pages will not load until they get a response from the API. This is, however, already the case for the index and discover pages.
Make sure all branded provider pages load properly.
> [EOSF-827] Check provider route slug against API

- app/routes/content/index.js
https://openscience.atlassian.net/browse/EOSF-826
Filter out non-bibliographic contributors from Google Scholar tags.
Passed in a filter to automatically remove non-bibliographic contributors from the list of contributors given to Google Scholar.
This ticket should just remove the non-bibliographic contributors from the meta tags, so please test to make sure that things appear (or don't appear) as they should.
> [EOSF-826] Remove non-bibliographic from Google Scholar

- app/components/search-facet-provider.js
- app/controllers/discover.js
- app/templates/discover.hbs
- config/environment.js
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-649
Allow facets to use the attribute `shareSource` in share queries on discover page.
Update: This ticket also makes changes in order to pass `whiteListedProviders` to the discover page (This aids the ember-osf portion of this issue).
Instead of just using the name of each branded preprint as a filter, `shareSource` will now be used if it is populated.
Note: The facets will show up as the `shareSource` instead of the provider names. This can be changed if desired as it is not particularly pretty.
`whiteListedProviders` in config no longer starts with lowercase elements.
> Feature/Use shareSource for facets [EOSF-649]

- app/styles/app.scss
- ember-cli-build.js
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-736
Update to use the newest osf-style via node_modules instead of bower.
Update ember-cli and remove some un-needed style imports.
Some unused imports were removed or updated.  Please check that preprints doesn't have any unexpected styles or behaviors.
> [EOSF-736] Update to get osf-style from node_modules

- app/controllers/content/index.js
- app/templates/content/index.hbs
https://openscience.atlassian.net/browse/MOD-146
`preprint-status-banner` breaks on preprints with state `initial` and is confusing/contradictory on preprints with private nodes.
Hide `preprint-status-banner` on private and abandoned preprints
None.
> [MOD-146][Fix] Hide status banner on private and abandoned preprints

- CHANGELOG.md
- ember-cli-build.js
https://openscience.atlassian.net/browse/EOSF-859
Update the ember.js cdn to point to the minified 2.8.3.
> [EOSF-859] Update ember.js cdn version to 2.8.3

- app/locales/en/translations.js
- app/templates/content/index.hbs
Users don't know when they will have a DOI for their preprint.
Add "DOI created after moderator approval." on pending pre-moderation preprints
https://openscience.atlassian.net/browse/MOD-159
> [Improvement][MOD-159] Add DOI message - Preprints

- CHANGELOG.md
- tests/integration/components/provider-carousel-test.js
- tests/integration/components/search-facet-taxonomy-test.js
Fix the `provider-carousel` and `search-facet-taxonomy` component integration tests so they work with Firefox.
* in `provider-carousel` test: use a RegEx to account for possible whitespace.
* in `search-facet-taxonomy` test: use innerText instead of non-standard outerText
Tests should now pass in Firefox.
https://openscience.atlassian.net/browse/EOSF-886
> [EOSF 886] make tests work in firefox

- app/components/provider-carousel.js
- app/components/search-facet-provider.js
LiveData needs to be filtered out from the available preprint providers on the discover page.  This is done through removing if the id is equal to `asu` (its old ID).  LiveData has recently been updated with a new id of `livedata`.  The filter needs to be updated with the new id in order to keep filtering out LiveData. 
Update the id being filtered from `asu` to `livedata`.
This should fix the issue of LiveData appearing on the discover page, but please make sure that it removes it completely (on the list, carousel, etc.)
None
> [Hotfix] Change LiveData's filtered id

- CHANGELOG.md
- app/controllers/content/index.js
- app/locales/en/translations.js
- app/templates/content/index.hbs
- tests/unit/controllers/content/index-test.js
Change wording on "Edit preprint" button to "Edit and resubmit" on preprint detail page if the preprint is rejected and the workflow is pre-moderation.
Why:
Some users might think to resubmit means go through the submission process again instead of editing their current preprint and resubmitting.
- Use a computed property to determine the wording based on provider's review workflow and preprint status.
- Update translation file
- Update changelog
https://openscience.atlassian.net/browse/MOD-182
> [Improvement][EOSF-914] Update edit button wording

- CHANGELOG.md
- app/templates/index.hbs
At the moment, unbranded preprints is using hard-coded data for the advisory board.  We should be using data from the admin app.
Remove hard-coded section and altered the conditional that determines when to show it.
https://openscience.atlassian.net/browse/EOSF-950
> [EOSF-950] Hotfix - remove hard-coded advisory board

- CHANGELOG.md
- app/locales/en/translations.js
- app/templates/components/preprint-navbar-branded.hbs
To add the donate button to the branded navbar.
Add donate button (without special styling)
The donate button should show up on branded preprints, with the same styling as the other buttons.  It should not have any styling like it does on the OSF side (mainly just no green text).
https://openscience.atlassian.net/browse/EOSF-952
> [EOSF-952] Add donate button to branded navbar

- CHANGELOG.md
- app/components/search-facet-taxonomy.js
If the user has some subjects selected when navigating to the `Discover` page, the subject list will only show the top-level subjects regardless of whether or not other level subjects have been selected.  This makes it look like you haven't selected any second or third level subjects.  This change will auto-expand all of the subjects you have selected.
- Add functions that will break up the `activeFilters` and query for subjects based on each level
The changes added will loop through each level of the subjects list based on the `activeFilters` and expand them if they have a child selected.  They will *only* expand if at least one child is selected.  So no matter if the top-level subject is selected or not, if there is a child selected it should expand.  
Please be sure to test that all …
> [EOSF-672] Add auto expansion on selected subjects

- package.json
- yarn.lock
Fixes have been done in `ember-osf` to get the dropzone area clickable on preprints again.  This PR updates to the latest `ember-osf` to use those changes.
Update `yarn.lock` file and use the latest `ember-osf`
https://openscience.atlassian.net/browse/EOSF-951
> [EOSF-951] Update to use latest ember-osf

- CHANGELOG.md
- app/index.html
If the user does not have JavaScript enabled on their browser, preprints shows up as a blank white screen.  This will add an error message and a link that shows users how to enable JavaScript to use the site.
- Add `<noscript>` message
https://openscience.atlassian.net/browse/EOSF-889
> [EOSF-889] Add JavaScript disabled message

- CHANGELOG.md
- app/locales/en/translations.js
- app/templates/content/index.hbs
- package.json
- yarn.lock
This PR complements [the previous PR](https://github.com/CenterForOpenScience/ember-osf/pull/330) to show alert when DOI is being minted.
In `translation.js`, a prompt message for doi being minted is added.
In `templates/content/index.hbs`, the template is changed to show the prompt message when DOI is being minted.
None
https://openscience.atlassian.net/browse/EOSF-879
> [EOSF-879] Update preprint to show alert when DOI is being minted.

- app/index.html
- app/routes/application.js
The newest version prerender uses Chrome to render pages and is aggressive about not waiting for async requests. In order to guarantee that the entire page is loaded rendered, we need to set `window.prerenderReady = false` when the page first loads, and once the rendering is complete, set `window.prerenderRead = true`
Ref: 
* https://prerender.io/documentation/best-practices
* https://github.com/prerender/prerender/blob/c63413ac2359144f16641874dc0a748c075515f1/lib/browsers/chrome.js#L435-L455
Adds script to index.html and application route didTransition action hook
@jamescdavis  @CenterForOpenScience/reviews we'll need to do this in the other ember repositories as well. Preprints has the slowest page load time, so this is the priority.
Once this is up on staging/production, add …
> [hotfix] Add settings for prerender

- CHANGELOG.md
- app/components/error-page.js
- app/styles/app.scss
- app/styles/error-page.scss
Currently, the color contrast for support email link on ECSarxiv and EarthArxiv error pages are not enough. This PR fix the issue.
Change the component's CSS class to 'prerpint-header' and 'preprint-hearder-error'.
Added a style file to the component to add padding and bottom margin.
The error page for OSF preprint would also be changed to using the background image on the landing page, which should be more consistent.
https://openscience.atlassian.net/browse/EOSF-881
> [EOSF-881] Fix contrast issue for error pages.

- CHANGELOG.md
- app/components/preprint-status-banner/component.js
- package.json
- tests/unit/controllers/content/index-test.js
- tests/unit/controllers/submit-test.js
- yarn.lock
This is the second PR to the [previous one](https://github.com/CenterForOpenScience/ember-osf/pull/329) for `action` model renaming.
in `components/preprint-status-banner`, because the newly renamed `review-action` model is associated to the `preprint` model with a new key `reviewActions` instead of `actions` (see [this line](https://github.com/CenterForOpenScience/ember-osf/pull/329/files#diff-17a82615d478139017c35d835342db7aL39) in the previous PR.), `submission.actions` is changed to `submission.reviewActions`.
https://openscience.atlassian.net/browse/EOSF-885
> [EOSF-885] Review action rename.

- app/routes/content/index.js
didTransition is not bubbling, causing prerender to timeout (`window.prerenderReady` is always `false`)
> Bubble didTransition event in the content route

- app/index.html
Change wording of `noscript` message if JavaScript is disabled.
Change `noscript` message to say: `For full functionality of this site it is necessary to enable JavaScript. Here are instructions for enabling JavaScript in your web browser.
https://openscience.atlassian.net/browse/EOSF-889
> [EOSF-889] Feature/fix noscript message if javascript disabled

- app/services/theme.js
- config/environment.js
- tests/unit/services/theme-test.js
Currently, the `og:image` meta tags for OSF Preprint reference to an incorrect asset. This change should fix that to refer to fingerprinted assets in our osf-assets repo. 
In `theme.js`, OSF Preprint's `logo.path` is no longer referencing to assets in ember-osf-preprints. Instead, it is changed to use the same `buildProviderAssetPath` method that builds fingerprinted assets urls for all provider assets.
Therefore, `environment.js` is changed to remove the `providers` list that includes information that is no longer necessary for building OSF Preprint assets.
None
https://openscience.atlassian.net/browse/EOSF-839
> [EOSF-839] Make use of fingerprinted osf-assets for OSF Preprint logoSharing

- CHANGELOG.md
- app/locales/en/translations.js
- app/styles/app.scss
- app/templates/index.hbs
- package.json
- yarn.lock
The subject list on the index page should reflect if a preprint provider has highlighted subjects.  We should change the wording from `Browse by subjects` to `Browse by featured subjects` if the provider has those subjects highlighted.
- Add translations for `Browse by provider`, `Browse by subject`, and `Browse by featured subject`
- Add conditional to check for `has_highlighted_subjects` flag
In the case that a provider has highlighted subjects: 
Else, the normal text will display:
https://openscience.atlassian.net/browse/EOSF-884
> [EOSF-884] Fix wording if provider has highlighted subjects

- CHANGELOG.md
- app/controllers/submit.js
- package.json
- yarn.lock
Users can still redirect away from the preprint submission page when clicking `Save and Continue` after each form block.
Added to the already existing `computed.or` to determine if the user is adding or editing a preprint.  Will default to `True` if adding.
This will prevent the user from leaving the page at all when uploading and creating a preprint.  The user shouldn't be able to redirect when:
- In the middle of editing a section
- After clicking `Save and Continue` between sections (even when nothing else has been started/changed)
When the user is editing a preprint, the user can leave the page unless they have any dirty fields.  So the user should not be able to redirect when:
- They've changed anything without hitting `Save and Continue`
They should be able to redirect when:
- …
> [IN-67][Preprints]  Add conditional to prevent redirect at any point in preprint submission

- app/styles/app.scss
- app/templates/index.hbs
* allow Preprint provider logos display on preprints index page to use full container width
* make Preprint provider logos links again
* remove `max-width` on logos container
* move logos and contact containers to within preprint services container
* change to `flex-basis: auto`
* change logo `div` tags to `a` tags that link to provider and `display:block`
Make sure this works correctly in all supported browsers. Flexbox is supposed to be [fully supported in all major browsers](https://caniuse.com/#feat=flexbox), but apparently has some bugs in IE 11 (see the Known Issues tab).
https://openscience.atlassian.net/browse/IN-72
> [IN-72] improve preprint logo visibility on osf preprints landing page

- app/routes/content/index.js
During testing, @laurenrevere found out that the og:image url on staging is malformed. This fixes the issue.
A conditional is added to prepend `origin` to `imageUrl` and `secure_url` only if `image.path` is not already a full url.
Check that staging no longer has malformed og:image url. After that you should be able to test Twitter and Facebook sharing.
https://openscience.atlassian.net/browse/IN-73
> [IN-73] Fix malformed url of og-image on staging

- app/templates/index.hbs
Fix issue with branded domains not working
Use route-prefix helper for discover link instead of assuming the provider route.
Branded domains should work again.
https://openscience.atlassian.net/browse/IN-124
> [IN-124] Use route-prefix helper for discover link

- CHANGELOG.md
- tests/integration/components/convert-or-copy-project-test.js
- tests/integration/components/supplementary-file-browser-test.js
To update tests that were skipped due to updated dependencies.
- Un-skip tests in `convert-or-copy-project-test` and `supplementary-file-browser-test`
- Update query in `supplementary-file-browser-test` to use `queryHasMany`
No noticeable front-end changes.  It should just make the tests run instead of being skipped.
https://openscience.atlassian.net/browse/IN-20
> [IN-20][Preprints] Update skipped tests

- app/controllers/submit.js
If there isn't a file selected, the user shouldn't be warned about leaving the submission page.
Add to `hasDirtyFields` to check if there is a file selected before showing the message to users
With these changes there should be four use cases to check for.  The warning message should pop up for user when:
- User is uploading a preprint and has selected their file
- User is editing a pre-existing preprint and has made changes
The message should not show up when:
- User goes to submission page and has not chosen a file to upload (or has clicked the back button on the submit block)
- User goes to edit page and hasn't made any changes to the file
https://openscience.atlassian.net/browse/IN-67
> [IN-67][Preprints] Remove redirect warning from submission page if no file selected

- CHANGELOG.md
- app/controllers/index.js
- app/templates/index.hbs
To change the 'Powered by Preprints' link to stay on the current server.
- Use `config.OSF.url` instead of a hard-coded link
This should only affect the 'Powered by Preprints' link on the index page of branded preprints.
The link should still point to `/preprints`, but the prefix should change according to whichever server you're currently on (i.e. `staging.osf.io/preprints`)
https://openscience.atlassian.net/browse/IN-29
> [IN-29][Preprints] Change 'Powered by Preprints' link to stay on current server

- CHANGELOG.md
- app/controllers/submit.js
If the user doesn't make any changes on the submit page, the warning modal shows up anyway when they try to leave.  It should only show up if the user has added a file/made changes.
- Separated the check for if there is a file uploaded && you're adding a file
- Added onto that check for whether or not user selected a node instead of uploaded a file
There are a few cases to check:
- If the user goes to submission page: **should not display warning**
- If the user uploads a file: **should display warning**
- If the user selects a node: **should display warning**
https://openscience.atlassian.net/browse/IN-175
> [IN-175][Preprints] Remove warning modal on submit page if there haven't been changes

- CHANGELOG.md
- app/controllers/content/index.js
- app/routes/content/index.js
- tests/unit/controllers/content/index-test.js
Use the new `facebookAppId` property as the Facebook app ID for branded providers if it's available.
- Use branded provider's Facebook app ID in the meta tags and in the share button
ID specified in the admin app
ID shows up in the URL when going to share the link
ID shows up in the meta tags
This should use the `facebookAppId` for branded providers if they have an app ID specified in the admin app.  It should change the Facebook app ID in the meta tags and when sharing a preprint.
https://openscience.atlassian.net/browse/IN-31
> [IN-31][Preprints] Use facebookAppId if available for branded preprints

- CHANGELOG.md
- app/styles/app.scss
Make the preprint provider logos smaller on the OSFPreprints landing page.
Reduced the height and min-width of the preprint provider logos on the OSFPreprints landing page.
**Before:**
**After:**
Check the logos at multiple screen widths.
https://openscience.atlassian.net/browse/IN-169
> [IN-169][Preprints] Make the preprint provider logos smaller

- CHANGELOG.md
- app/components/subject-picker/component.js
Show all of the available subjects on the preprint submission page.
Change page size from 100 --> 150.
Impacts anyone who allows all of the "Law" subjects (lawarxiv, frenxiv, osf, arabixiv, thesiscommons, inarxiv).
Easiest way to check that the page size has increased is to click on the law category while the console is open and look at the request on the Network tab (can filter to XHR).
https://openscience.atlassian.net/browse/IN-183
> [IN-183][Fix] Increase page size to 150 for taxonomies

- CHANGELOG.md
- app/components/convert-or-copy-project.js
- app/components/file-uploader.js
- app/components/preprint-form-project-select.js
- app/components/preprint-title-editor.js
- app/controllers/content/index.js
- app/controllers/submit.js
- app/mixins/setup-submit-controller.js
- app/routes/content/index.js
- app/templates/components/file-uploader.hbs
- app/templates/components/preprint-form-header.hbs
- app/templates/components/preprint-form-project-select.hbs
- app/templates/components/preprint-title-editor.hbs
- app/templates/content/index.hbs
- app/templates/submit.hbs
- tests/integration/components/convert-or-copy-project-test.js
- tests/integration/components/preprint-title-editor-test.js
- tests/unit/controllers/content/index-test.js
- tests/unit/controllers/submit-test.js
Grab more data from the preprint model instead of the node
- Update the submit controller to save more data (title, tags, description) on the preprint model
- Update content controller and template to retrieve more data from preprint model
- Replace terminologies or variable names to reflect the changes.
- Update tests
The changes in this ticket affect preprint `submit` and`detail` pages.
- On the preprint submit page:
- At each section, make sure to fill out the info including the non-required fields: `tags, description, title` should not be blank to test this ticket.
- Make sure each section saves without errors (developer console or errors growlers)
- Visit the preprint you just created, and make sure there are no errors and
all the preprint info you entered is available, especially …
> [IN-97][Preprints] Get more data from preprint model

- CHANGELOG.md
- app/templates/content/index.hbs
This is the second of two PRs (the first one is [here](https://github.com/CenterForOpenScience/ember-osf/pull/346)) to make sure preprint detail page will fall back to using fullName of contributors.
In `index.hbs`, use newly added `name` field of the `user` model.
There are four scenarios to test:
1. givenName, familyName and fullName are all defined: should show "{givenName} {familyName}"
2. only givenName and fullName are defined: should show "{fullName}"
3. only familyName and fullName are defined: should show "{fullName}"
4. only fullName is defined: should show "{fullName}"
Note: fullName is always defined because it is a required field for users.
https://openscience.atlassian.net/browse/IN-23
> [IN-23][Preprints] Fall back to use fullName when user have no givenName and familyName

- CHANGELOG.md
- app/controllers/content/index.js
- package.json
- tests/unit/controllers/content/index-test.js
- yarn.lock
When a user clicks on the Linkedin sharing button on some preprints with Unicode encoded strings as titles or descriptions, the pop-up sharing page says "page not found". This is because Linkedin sharing works quite differently in that it gets sharing information from the query parameters of the sharing URL, which we construct on the front end side. Because javascript is not Unicode-aware, when we truncate Unicode strings according to specified length limit, it breaks the encoding and therefore causing errors for Linkedin when parsing the URL. 
This PR fix the problem by using an NPM package to do Unicode-aware string truncating.
An NPM package `unicode-byte-truncate` is added as a dependency.
In `controllers/content/index.js`, `trunc` from the newly added dependency is used to truncate …
> [IN-45][Preprints] Truncate unicode strings correctly for Linkedin sharing.

- app/controllers/submit.js
Fix a bug where default license was not not updated when changing providers.
Clear the default license when saving the provider so that it is forced to be reset to the first license in the updated list of available licenses.
Make sure saving basics works for a provider that does not include the default OSF license.
https://openscience.atlassian.net/browse/IN-76
> [IN-76] [Preprints] Clear previous basicsLicense.licenseType when changing providers

- app/components/file-uploader.js
- app/controllers/submit.js
- app/mixins/setup-submit-controller.js
- app/templates/components/preprint-form-project-select.hbs
- app/templates/submit.hbs
Fix issue where validation indicators on `upload` and `discipline` sections
stay red after saving that section.
- Update save action to use preprint instead of node model.
- Fix `disciplineChanged` computed property by using `subjectIdMap`.
Follow up PR to https://github.com/CenterForOpenScience/ember-osf-preprints/pull/526
On the preprint submit page, make sure the icons turn green from red when you save the section
both in upload or edit mode. 
[IN-97](https://openscience.atlassian.net/browse/IN-97)
> [IN-97][Preprints] Fix validation icons

- app/components/file-uploader.js
- app/controllers/submit.js
Not updating the existing node on preprint changes seems to cause lots
of issues.
Modify `uploadFileToExistingNode` to save changes both on the `preprint` and `node` models.
[IN-97](https://openscience.atlassian.net/browse/IN-97)
> [IN-97][Preprints] Keep node updates on preprint changes 

- CHANGELOG.md
- app/controllers/submit.js
Branded domains can't search for contributors to add.
Introduced by the 0.118.0 release: https://github.com/CenterForOpenScience/ember-osf-preprints/commit/21847af63c170d8f2bf3e1ca73032d8e5cad7d46
Set the base url of the request to `config.OSF.url` instead of using a relative url.
Contributor search should work for both branded and unbranded providers.
https://openscience.atlassian.net/browse/IN-205
> [IN-205][Preprints] Use url from config for search request

- CHANGELOG.md
- app/styles/app.scss
Improve spacing of preprint logo display
* restrict provider logo width
* center justify content within provider logos container
Check on all browsers.
https://openscience.atlassian.net/browse/IN-190
> [IN-190][Preprints] Improve spacing of preprint logo display

- app/templates/submit.hbs
Fix issue where upload section isn't open for branded submission pages.
* Add `open=(and theme.isProvider (not editMode))` to upload section.
* Break the line into multiple so it's easier to read
For branded providers the upload section on the submit form should be automatically open.
For the OSF's submit form the providers section should be automatically open and the upload section should open after a provider has been selected.
https://openscience.atlassian.net/browse/IN-237
> [IN-237][Preprints] Open upload section for branded providers

- app/components/preprint-form-header.js
Remove unused property after #548 fix.
Remove `providerAssetsURL` property from `preprint-form-header` component.
None.
https://openscience.atlassian.net/browse/IN-201
> [IN-201][Preprints] Minor cleanup of now unused property

- ember-cli-build.js
- tests/unit/controllers/content/index-test.js
Fix bootstrap sass import so that preprints loads properly.
- Move the `bootstrap-sass` asset path to the top of the sassOptions list
Should fix preprints.
None
> [Preprints] Fix Bootstrap Sass

- CHANGELOG.md
- app/styles/app.scss
- app/templates/components/preprint-navbar-branded.hbs
The branded navbar's styling doesn't match what is seen in ember-osf and osf.io
- Change formatting/classes/id's in `preprint-navbar-branded` to match what's required for osf-style
- Remove unnecessary padding and add padding to the logo to prevent squishy-ness on smaller screens with long names
This should make the branded navbar act the same way as the navbar on ember-osf apps and osf.io.
- It should cut off long user names and prevent it from breaking to a new line/run off the screen
- It should also keep cutting the name as the screen gets smaller
- Because this is branded, it should keep the old styling that's specific for the provider
** Note **
This should be used with the PR for the ember-osf side:
https://github.com/CenterForOpenScience/ember-osf/pull/387 …
> [IN-235][Preprints] Fix navbar on branded domains

- app/controllers/submit.js
- tests/unit/controllers/submit-test.js
Fix deleting tags when adding a preprint
Fix issue where tags are deleted from the tags box but the controller still
keeps the tags.
Fix the action handling removeTag to use arg as `tag` not `index`
[[IN-309]](https://openscience.atlassian.net/browse/IN-309)
> [IN-309][Preprints] Fix deleting tags

- app/components/preprint-form-section.js
- app/routes/application.js
External preprint domains aren't getting the right theme properties.
- Fix small bug that wasn't binding `this` when attaching the branded domain's theme
- Revert error action to use `sendAction` as an eslint exception
This should fix external domains.  Namely fixes two big issues:
- Preprints were infinitely reloading (between the domain and the osf domain like staging-osf)
- Provider carousel was appearing on the submit page of branded domains
https://openscience.atlassian.net/browse/IN-306
> [IN-306][Preprints] Fix bug on external branded preprint domains

- app/controllers/submit.js
- app/routes/submit.js
- tests/unit/controllers/submit-test.js
The submit page shows a warning modal on navigation even if you haven't done anything.
* Switched title default to `''` instead of `null` to prevent a false positive when checking equality (e.g., null === undefined returns false). 
* Split some of the long line into a variable so it's easier to read
Generally the defaults should match the type that will be in that field to prevent this kind of thing.
None expected
https://openscience.atlassian.net/browse/IN-315
> [IN-315][Preprints] Fix preprint warning modal

- app/components/supplementary-file-browser.js
- app/controllers/submit.js
`provider` was added to the supplementary-file-browser component in the template which caused a conflict when trying to set the file provider with the name `provider` in the controller. 
Renamed the file `provider` as fileProvider to avoid conflict. 
See original PR
https://openscience.atlassian.net/browse/IN-251
> [IN-251][Preprints] Fix sup file browser

- CHANGELOG.md
- app/components/search-facet-provider.js
- app/controllers/discover.js
- app/controllers/submit.js
- app/routes/content/index.js
- app/templates/components/preprint-form-header.hbs
- app/templates/submit.hbs
Use "OSF Preprints" instead of "Open Science Framework"
- Update search provider facet to use "OSF Preprints" (on discover page)
- Update `filterReplace` to sub with "OSF Preprints"  in lieu of "OSF"
- Fixed `whiteListedProviders` to handle case where is still `undefined`
Please make sure that 
- the search provider facet on discover page left pane uses "OSF Preprints"
- on submit page, after selecting OSF Preprints and moving on to the next section, it shows "OSF Preprints"
- on preprint detail page, the publisher head meta tags use "OSF Preprints" for osf preprints.
[IN-255](https://openscience.atlassian.net/browse/IN-255)
> [IN-255][Preprints] Use "OSF Preprints"

- CHANGELOG.md
- app/components/preprint-form-project-select.js
Node parents sometimes show as private when searching for a project.
Embed node parent to allow parent title's to appear in the select project dropdown
Alex notes: Make sure that parents of projects don't say private when not private (see issue description). There are two functions that fetch the data, one for the first fetch and one for every fetch after. So make sure both the first fetch of data works and additional filtering works. Ask me (alex) if that isn't clear.
https://openscience.atlassian.net/browse/IN-198
> [IN-198][Preprints] Node parent title

- CHANGELOG.md
- app/router.js
- config/environment.js
- package.json
- yarn.lock
To add custom dimensions to our `trackPage` function.
- Add `authorized`, `resource`, and `isPublic` dimensions to the `trackPage` function
- Remove old version of `ember-metrics` since we're getting a newer version from `ember-osf`
There should be three new dimensions that you see in a trackPage request:
If the page is discover, index, or submit/edit:
authorized => [whether or not the user is logged in will be true or false]
isPublic => [n/a]
resource => [n/a]
If the page is content/detail page:
authorized => [whether or not the user is logged in will be true or false]
isPublic => [public]
resource => [preprint]
https://openscience.atlassian.net/browse/IN-180
> [IN-180][Preprints] Track custom dimensions in Google Analytics

- app/templates/components/search-facet-provider.hbs
Check box in the provider facet for branded provider on the discover page.
Before:
After:
Check that the provider is checked when it should be and not when it shouldn't be. Probably covered in general regression testing.
https://openscience.atlassian.net/browse/IN-305
> [IN-305][Preprints] Both check and disable box if theme.isProvider

- app/templates/submit.hbs
Missing preprint word.
Before:
Make sure preprint word is present in abstract placeholder.
No ticket
Did not test this locally.
> [No Ticket][Preprints] Pass documentType to abstract placeholder translation

- app/controllers/submit.js
- tests/unit/controllers/submit-test.js
Clicking the Sidebar add preprint button on the discover page while not logged throws a prompt from the discover page for dirty fields on the submit page. If you reject this redirect (to the login page) you will be able to stay on a broken not logged in submit page. 
Fixed fields that are dirty before the model is properly set so the dirty fields should not trigger the page change confirmation dialogue. This should prevent the bad behavior. 
Code wise, I added checks for basicsLicense name and year needing to not be null for them to be dirty. The year cannot be nullified through the UI (backspacing the whole 2018 resets it back to the current year) and the license name should never be a proper null value. 
1. Confirm no redirect confirmation when pressing the button.
2. Regression of the …
> [IN-365][Preprints] Fix submit preprint from discover page redirect error

- app/styles/app.scss
- app/templates/components/preprint-navbar-branded.hbs
Preprints breaks on small screens on providers with long names
We lost some margin on the right with recent changes.
Production:
Left: Staging1
Right: Staging2
1. Remove the preprint word at very small sizes (<520px, arbitrary point that worked)
2. Remove some extra margin at small sizes (dumb I know, I feel bad doing it this way). 
Check long providers at breakpoints to make sure they still look good on test. None should break now.
https://openscience.atlassian.net/browse/IN-261
> [IN-261][Preprints] Fix navbar small screens 

- app/components/preprint-form-section.js
The collapsible panel on the submit/edit page is currently broken for the Upload section.  When clicked, the panel doesn't collapse and instead just gets obnoxiously tall.
- Removed code that changed the height of the internal elements on click
The issue was that the Upload section's height would grow really tall when clicked a second time when it was already opened.
On the submit/edit page:
- Fill out the upload section and continue
- Click on the upload section again, make sure it works as expected.  Make sure that all of the internal collapsible panels open and close properly.
- Click on the upload section one more time.  It shouldn't collapse or expand, and it should stay the same height.
This can also affect the other panels, so please be sure to also test this on all of the other …
> [IN-261][Preprints] Fix collapsible panel animation on submit/edit page

- CHANGELOG.md
- config/environment.js
As noted in https://github.com/CenterForOpenScience/ember-osf-preprints/issues/459, the original environment check that we were doing would always evaluate the first check as an array and would always be truthy.  This would prevent the second part from being checked.
Changed:
`[process.env.KEEN_ENVIRONMENT] || ['production']`
to:
`[process.env.KEEN_ENVIRONMENT || 'production']`
This shouldn't have any noticeable affects on the front end.  You should still be able to see Google Analytics and Keen working normally.
https://openscience.atlassian.net/browse/IN-180
`N/A`
> [IN-180][Preprints] Fix environment variable check

- app/routes/provider/discover.js
Fix the problem where discover pages for branded providers are not loading.
In `route/provider/discover.js`, the model for the controller is set to `model.preprintProviders` because the `model` hook in `route/discover.js` has changed from returning the result of the `query` to returning a object whose `preprintProviders` contains the result.
> [Noticket] Fix discover page for branded providers.

- app/components/search-facet-provider.js
- app/controllers/discover.js
Fix isssue where selecting OSF Preprints filtered the preprints by `?provider=OSF Preprints` and
Share does not know what `OSF Preprints` is. So we keep it `OSF`.
On the discover page, on the left pane, select OSF Preprints and make sure you see the filtered results (just OSF Preprints). and URL is `https://staging2.osf.io/preprints/discover?provider=OSF` not `https://staging2.osf.io/preprints/discover?provider=OSF Preprints`
[IN-353](https://openscience.atlassian.net/browse/IN-353)
> [IN-353][Preprints] Fix facet filter for OSF Preprints

- app/locales/en/translations.js
- app/templates/components/add-preprint-box.hbs
- tests/integration/components/add-preprint-box-test.js
We miss the button for discover page when changing the languages.
For the discover page, `Add your preprint` button is changed to `Add a preprint` for non-moderated providers and `Submit a preprint` for moderated providers.
https://openscience.atlassian.net/browse/IN-117
> [IN-117] Change discover page button

- CHANGELOG.md
- app/styles/app.scss
- app/templates/content/index.hbs
Wrap preprint license text on spaces instead of in the middle of the word.
* Use `break-word`
* Use CSS classes
Make sure licenses look correct.
[[IN-131]](https://openscience.atlassian.net/browse/IN-131)
> [IN-131][Preprints] Break-word correctly in licenseText

- CHANGELOG.md
- app/styles/app.scss
From ticket
>Reduce line height on footer text when wrapping. It doesn't look like the text is all one thing if the space between the wrapped text is the same as the space between the other lines.
* Remove `line-height`
Should only affect footer, make sure it looks right on small screens
[[IN-128]](https://openscience.atlassian.net/browse/IN-128)
> [IN-128][Preprints] Remove branded footer line-height

- CHANGELOG.md
- app/components/supplementary-file-browser.js
- app/locales/en/translations.js
- app/locales/es-disabled/translations.js
- app/styles/_variables.scss
- app/styles/app.scss
- app/templates/components/supplementary-file-browser.hbs
- app/utils/file-download-path.js
- package.json
- tests/integration/components/supplementary-file-browser-test.js
- tests/unit/utils/file-download-path-test.js
Based on @binoculars PR https://github.com/CenterForOpenScience/ember-osf-preprints/pull/285
Allow versions of preprint or suppl. files to be downloaded from the preprint detail page.
ht @binoculars 
- Updated `supplementary-file-browser` to support downloading file versions
- Updated/fixed and added tests 
....coming soon after demo.
>>> [IN-363 ](https://openscience.atlassian.net/browse/IN-363)
http://recordit.co/uDykCHmWSo
**latest: ** http://recordit.co/UZ0S0MYly0
> [IN-363][Preprints] Allow downloading previous versions of preprints and/or suppl. files

- CHANGELOG.md
- app/locales/en/translations.js
- app/locales/es-disabled/translations.js
- app/templates/components/preprint-navbar-branded.hbs
To update the branded navbar to match the non-branded version.
- Added `My Preprints` link
- Removed `My OSF Projects` link
- Updated translations
Please make sure that the link takes you to the right anchor on the My Projects page and that the navbar breaks to the smaller version when it needs to.
https://openscience.atlassian.net/browse/IN-273
`N/A`
> [IN-273][Preprints] Add 'My Preprints' link to branded navbar

- app/components/subject-picker/component.js
Filtering when there aren't any subjects is breaking the submit/edit page.
- Add a check for subjects before trying to return a filtered list
The issue before was that this would try to filter subjects that weren't existent and caused a glimmer error that would break the page.  By fixing the filter, you should notice that even when you try to filter a box without subjects the page won't break and you can finish the form.
- Create a new preprint
- Select engrxiv as the provider
- Complete form up to the subjects
- Select `Engineering` in the first box and `Other Engineering` in the second
- Notice that there aren't any subjects appearing in the third box
- Try filtering in the third box.  Notice that there aren't any errors in the console
- Save subjects
- Reopen subject section and try …
> [IN-459][Preprints] Fix subject filter on edit/submit page

- app/styles/app.scss
Fix the license text formatting on the preprint-detail page to also work on Firefox, IE, and Edge.
- Change `word-break: break-word` to `word-break: normal`
This should affect the license text on the detail page.  It should break the whole word to a new line instead of break it in the middle of a word.
*Screenshot taken in Firefox 62*
https://openscience.atlassian.net/browse/IN-131
`N/A`
> [IN-131][Preprints] Fix license text formatting

- app/components/supplementary-file-browser.js
Currently, when using non-direct file download URL such as https://staging2.osf.io/download/mejtw/?version=5&displayName=job-posts-lingo-2018-09-10T13%3A48%3A57.210Z.jpeg, the downloaded file still preserves the original name "job-posts-lingo.jpeg" as opposed to what's passed in `displayName` i.e "job-posts-lingo-2018-09-10T13:48:57.210Z.jpeg".
This is a workaround WB bug [SVCS-916](https://openscience.atlassian.net/browse/SVCS-916)
suggested by Fitz. 
Use direct download url by swapping file guid and "download"
So https://staging2.osf.io/download/mejtw/?version=5&displayName=job-posts-lingo-2018-09-10T13%3A48%3A57.210Z.jpeg
becomes
https://staging2.osf.io/mejtw/download/?version=5&displayName=job-posts-lingo-2018-09-10T13%3A48%3A57.210Z.jpeg
Please make sure the downloaded preprint …
> [IN-363][Preprints] Fix primary file versions downloadUrl

- CHANGELOG.md
- app/templates/components/preprint-form-header.hbs
Fix selected provider name on submit form.
Currently, on the submit form (provider section), after selecting a provider and moving on to the next section/pane, the name stays OSF Preprints with the logo of the selected provider.
- Replace `theme.isProvider` check with `provider.name` check.
- Update changelog
Please make sure both logo and provider name correspond to the selected provider after selecting provider and moving on to 'upload'.
[IN-472](https://openscience.atlassian.net/browse/IN-472)
> [IN-472][Preprints] Fix selected provider name on submit form

- app/routes/content/index.js
Change metatag from `citation_publication_date` to `citation_online_date` to allow Google scholar to better index our Preprints.
Same as above.
https://openscience.atlassian.net/browse/IN-479
> [Hotfix][IN-479][Preprints] Change metatag from `citation_publication_date` to `citation_online_date`.

- app/components/chronos-submission-panel/component.js
Chrome blocks new tab (popups) if it is not a result of a direct user action. This PR avoids that by first opening a new tab, then redirects the new tab to the url returned when a Chronos submission is completed.
> [Chronos] Bypass popup blocker

- app/components/preprint-file-renderer.js
- app/templates/components/preprint-file-renderer.hbs
Instead of building url to pass to MFR, pull url off of primary file download links (similar to pre-divorce, except it was pulling off of selectedFile.
This should be an improvement, and closer to what we have on prod (prior to the divorce). Building the download URL manually worked fine locally, but was failing on staging3. 
> Fix/Divorce - Rendering of Preprint File [IN-98]

- app/routes/content/index.js
Make it render less slooooowly
Previously, would block rendering waiting for all contributors to load and be inserted in `<meta>` tags. This is neither necessary nor helpful outside of prerender. Only block like that in prerender.
There are deeper problems here this PR does not attempt to fix. For example:
- We should avoid loading the full list of contributors
- If we have to load the full list of contributors, we should do it only once, not twice
- The list of contributors in `<meta>` tags is filtered to bibliographic contributors only. Should the displayed list of contributors be filtered also?
`<meta>` tags for all contributors should still be there, contributors should still load, the page should render faster.
n/a
> [hotfix][no ticket] fix(perf): don't block render waiting for <meta>

- app/routes/content/index.js
This PR makes sure that `citation_doi` metatag is alwasy the preprint doi.
https://openscience.atlassian.net/browse/EMB-482
> [EMB-482][Preprints] `citation_doi` metatag should always use preprints doi.

- tests/integration/components/preprint-navbar-branded-test.js
Try to fix the annoying test failures [here](https://travis-ci.org/CenterForOpenScience/ember-osf-preprints/builds/486610124).
Cannot reproduce the test failures locally. However I've encountered similar problems before. The fix seems to be adding the `documentType` in the provider stub for tests. Don't know whether this will fix the problem, but it wouldn't hurt.
> [No ticket] Add documentType to `fakeProvider` stub

- CHANGELOG.md
- package.json
- testem.js
- tests/integration/components/file-uploader-test.js
- tests/integration/components/preprint-navbar-branded-test.js
- tests/unit/components/preprint-status-banner-test.js
- tests/unit/controllers/submit-test.js
- yarn.lock
This updates preprints to use the latest ember-osf, which includes the ability to handle CSRF tokens. It fixes tests that fail because they now need the current-user service.
- Use ember-osf@develop
- Added service:current-user to submit controller and preprint-status-banner unit test needs
Need to make sure Preprints basic functionality still works after enabling the `enforce_csrf` waffle switch.
https://openscience.atlassian.net/browse/EMB-411
I've tested locally with CSRF enabled and everything appears to be functional.
> [EMB-411] handle django csrf endpoints

- app/controllers/content/index.js
- app/templates/content/index.hbs
- config/environment.js
This moves enabling of Chronos submission to be based on a list of providers in config.
* create `isChronosProvider` computed property to look for preprint provider in config.
* conditionally render the chronos-widget based on this property
(this means that Chronos will not be enable for psyarxiv until it's added to config)
Need to make sure Chronos submission still functions for psyarxiv (once configured)
n/a
Should make sure Chronos submission is enabled *only* when configured.
> refactor: enable Chronos for providers from config

- app/components/preprint-status-banner/component.js
- app/components/preprint-status-banner/template.hbs
- app/controllers/content/index.js
- app/controllers/content/withdraw.js
- app/controllers/submit.js
- app/locales/en/translations.js
- app/router.js
- app/routes/content/edit.js
- app/routes/content/index.js
- app/routes/content/withdraw.js
- app/routes/provider/content/withdraw.js
- app/styles/app.scss
- app/templates/content/index.hbs
- app/templates/content/withdraw.hbs
- app/templates/submit.hbs
- package.json
- yarn.lock
This PR adds functionality for preprint contributors to request withdrawal of a certain preprint.
To allow contributors to request withdrawal of a certain preprint, the following changes are made:
- A new `withdraw` view with route `/withdraw` is added.
- The `submit/edit` view is changed so that uses can navigate to the `withdraw` view.
- The `index` view (preprint detail) is changed so that the status bar shows `pending withdrawal` status. It also shows the tombstone page if the preprint is withdrawn.
- The `preprint-status-banner` component is changed to show the `pending withdrawal` message.
The changes above are detailed below, respectively:
- For the `withdraw` view,
- Two route files, `routes/content/withdraw.js`, `routes/provider/content/withdraw.js` (for custom domain providers) …
> [Preprint Withdrawals][Preprints][EMB-550][EMB-549] Add contributor withdrawal of preprints; Preprint tombstone page.

- app/templates/content/index.hbs
A bad merge conflict resolution resulted in duplicate share rows on the preprint detail page.
Remove duplicate share row from preprint content page.
make sure there's not two share rows on preprint detail page.
n/a
n/a
> fix: remove duplicate share row

- app/controllers/content/withdraw.js
- app/controllers/submit.js
- app/locales/en/translations.js
- app/templates/content/withdraw.hbs
- app/templates/submit.hbs
This PR fixes some small bugs on Preprints app and makes some text and button changes:
- On preprint edit/submit page, the bottom buttons only appears after the provider finishes loading.
- Change text for withdraw view notices.
- Change tombstone page banner text.
- Move "Return to preprint" link on top left of edit page back to bottom as a button.
- For a preprint, non-admin contributors should not be able to see withdraw button on edit page.
https://openscience.atlassian.net/browse/EMB-548
> [EMB-548][ENG-233][ENG-237][Preprint Withdrawals] Fix languages and buttons.

- CHANGELOG.md
- app/styles/app.scss
- app/templates/components/claim-user.hbs
- package.json
The author list will contain line breaks after unregistered users when logged in and spaces before the comma when logged out.
* display wrapper div for bs-modal for claim use confirmation as inline 
* add `~`s to eat up spaces and line breaks inside the `li`
* removed newline at end of `claim-user` template
Make sure author lists render correctly when an unregistered user appears in the middle of the list when logged in and when logged out.
https://openscience.atlassian.net/browse/ENG-101
Styling the bs-modal wrapper div does not affect the modal that is rendered in the wormhole.
> [ENG-101] fix linebreaks and extra spaces in author list

- app/components/chronos-submission-panel/component.js
- app/components/chronos-submission-panel/template.hbs
Currently, hitting cancel button on chronos submission panel will cause the dropdown list to not work. Also, the filtering does not work. This PR fixes the problems.
https://openscience.atlassian.net/browse/ENG-583
https://openscience.atlassian.net/browse/ENG-585
> [ENG-583][ENG-585] Fix cancel button and filter

- CHANGELOG.md
- app/controllers/content/withdraw.js
- app/locales/en/translations.js
- app/templates/content/withdraw.hbs
Make preprint withdrawal request explanation required.
Before:
After:
Need to test that a withdrawal request cannot be made without providing a reason that is at least 25 characters long.
https://openscience.atlassian.net/browse/ENG-560
I've overridden `showErrorMessage` (by passing in `didValidate`) on the `validated-input` to ensure the error message is not shown until the "Request withdrawal" button has been pressed.
> [ENG-560] make preprint withdrawal request explanation required

- app/components/chronos-submission-status-list-row/template.hbs
Only show link if the link is returned from the API.
The link button should now show only if the user is a submitter of this chronos submission.
https://openscience.atlassian.net/browse/ENG-586
> [ENG-586] Only show chronos submission link to submitter

- app/components/preprint-status-banner/component.js
- app/components/preprint-status-banner/template.hbs
- app/locales/en/translations.js
- app/routes/content/index.js
- app/templates/content/index.hbs
- package.json
- tests/unit/components/preprint-status-banner-test.js
- yarn.lock
Modify preprint status banner. Add new state `Withdrawal rejected`.
Added class names and translation strings to add a new status `Withdrawal rejected`.
Now there are 5 states for the preprint status banner:
- Pending
- Accepted
- Rejected
- Pending Withdrawal
- Withdrawal denied
Make sure that for each state, the banner surface the corresponding comment (if any) for that state.
https://openscience.atlassian.net/browse/ENG-559
> [ENG-559] Modify preprint status banner to show corresponding statuses and reviewer comments.

- app/components/plaudit-widget/component.js
- app/components/plaudit-widget/template.hbs
- app/controllers/content/index.js
- app/routes/content/index.js
- app/styles/preprint-detail-page.scss
- app/templates/content/index.hbs
- config/environment.js
Add plaudit widget and only render it after meta tags are ready.
Make sure the plaudit widget shows up at the bottom when the preprint has a doi.
https://openscience.atlassian.net/browse/ENG-882
> [ENG-882] Add plaudit widget and use it after meta tags are ready

- app/components/file-uploader.js
- app/components/preprint-file-renderer.js
- package.json
- yarn.lock
Remove the constraint on the preprint app where users cannot upload another version of preprint file with different filename.
Also modify the `file-uploader` to change the filename after the upload is successful.
Make sure that the new version of files is properly rendered by MFR.
[ENG-37]
[ENG-1219]
[ENG-37]: https://openscience.atlassian.net/browse/ENG-37
[ENG-1219]: https://openscience.atlassian.net/browse/ENG-1219
> [ENG-37] [ENG-1219] Enable uploading of a preprint with different name and extension

- CHANGELOG.md
- app/styles/app.scss
- app/templates/submit.hbs
Having the upload bar displayed on preprints submission is confusing to users, since it looks like the file is having issues being uploaded.  This PR will remove the upload bar until the user clicks "save" and the file is actually in the process of being uploaded.
- Added styling to dropzone classes to hide/show the upload bar
- Added conditional class in the `submit` template for styling when uploading
- This should only affect when the user is uploading a new file on the submit/edit pages, but should be tested in all cases when a user tries to submit a new file in preprints
https://openscience.atlassian.net/browse/ENG-508
> [ENG-508] Remove upload bar unless the file is being uploaded

- app/locales/en/translations.js
To make it clear to initial users that the Chronos feature is a beta.
- Added `(beta)` to the translation
This will only add the `(beta)` to the end of the Chronos submission link.
https://openscience.atlassian.net/browse/ENG-1269
N/A
This will need to be reversed when Chronos is waffled on for everyone.
> [ENG-1269][Feature] Add 'beta' to Chronos submission link

- app/controllers/submit.js
- app/locales/en/translations.js
- app/templates/submit.hbs
- tests/unit/controllers/submit-test.js
Add placeholders to the preprint submission workflow for Sloan signals of trust
- Added waffle flags to submission page for COI, data availability, and prereg
- Add waffled Author Assertions placeholder
- Add waffled COI placeholder
- This is just to add a sections to be filled out in later PRs, so this does not require testing
[ENG-1435]
https://openscience.atlassian.net/browse/ENG-1435
- Waffle names should match what is found in https://github.com/CenterForOpenScience/ember-osf-preprints/pull/701
[ENG-1435]: https://openscience.atlassian.net/browse/ENG-1435
> [ENG-1435] Placeholder for new sections in submission workflow

- app/components/assertions-dropdown.js
- app/styles/author-assertions.scss
- app/templates/components/assertions-dropdown.hbs
Assertions dropdown overflows on the right for small screens (<769px) 
- On small screens; Use `calculatePosition` 
- On the preprint detail, mobile and tablet screens; the dropdown should be centered (just like
everything in the preprint header)
https://openscience.atlassian.net/browse/ENG-
- This is easier to accomplish in js compared to css, because the dropdown is (absolutely) positioned by `ember-basic-dropdown`.
> Center assertions dropdown on mobile

- app/controllers/submit.js
- app/locales/en/translations.js
- app/styles/app.scss
- app/templates/components/preprint-form-header.hbs
- app/templates/submit.hbs
- package.json
- tests/unit/controllers/submit-test.js
- yarn.lock
To add the COI section to the submit/edit page
https://openscience.atlassian.net/browse/ENG-1435
This will only be adding the COI section to the submit/edit page. The field itself will be unchecked on the first run through of the form. The form cannot be submitted until the user either checks `No` or `Yes` and fills out the description box. The submit button at the end of the form will be disabled until that section is also valid, and will show `Conflict Of Interest` in the list of necessary fields still required for submit. The `describe` box will have a validation of 10 words minimum and a 5000 word limit. A validation message should appear at the bottom of the textarea if the user tries to move on without meeting those validations.
> [ENG-1435] Add coi section to submit page

- app/components/multiple-textbox-input.js
- app/styles/app.scss
- app/templates/components/multiple-textbox-input.hbs
- tests/integration/components/multiple-textbox-input-test.js
- Add a component to handle a variable amount of text inputs. Needed for Sloan Signals of Trust feature for users to add links.
- Added component `multiple-textbox-input`
- takes `placeholder` and `textFields` argument. `textFields` is a string[] that is used to populate this field if there are values already present.
- There are some cases where it can remove the wrong textbox, but I'm having trouble narrowing down when/why this happens. And occasionally the `Add` button can get put between the `Remove` buttons, but this is also very sporadic. Not sure how to reproduce.
- Please test when textfields are already populated (i.e.: a user edits a preprint with data links or prereg links already filled out)
https://openscience.atlassian.net/browse/ENG-1435
- Please let me know if there are …
> [ENG-1435]Add component to handle multiple text inputs

- app/templates/submit.hbs
The `Yes` and `No` radio button's `checked` status should depend on `hasCoi`.
> [No ticket] Fix coi yes button

- app/routes/content.js
- tests/unit/routes/content-test.js
- tests/unit/routes/provider/content-test.js
In the `content` route, we fire an extra `v2` request for the waffle flags because somehow the first request sent upon app initialization doesn't get the correct flags.
> [LukewarmFix] Make another v2 request on content route

- app/controllers/submit.js
- app/templates/submit.hbs
Fix the update bug by resetting the fields when user changes options.
Also change from `input` to `textarea` so that the placeholder text will wrap.
> Fix update bug. Placeholder text should wrap.

- app/styles/app.scss
- app/templates/components/assertions-links.hbs
In preprint submission workflow, disabled teaxtarea for sloan prereg link and public data should not be resizable.
In preprint detail page, clicking on sloan assertion links should open new tabs.
> [No ticket] Disabled  textarea should not be resizable; open link in new tab.

- app/components/multiple-textbox-input.js
- app/controllers/submit.js
- app/templates/submit.hbs
- tests/integration/components/multiple-textbox-input-test.js
This PR do three things:
- Show helpful error messages returned from the backend when the url input for data links/prereg links are invalid.
- Fix various save error due to how we PATCH data.
- Fix "Discard Changes"  not working when removing links.
- Take error from API response and toast that error in `_failMoveFromAuthorAssertions`.
- Modify `multiple-textbox-input` component.
- Instead of relying on `valuePath`, we directly pass the computed property into the component for updates so that "Discard changes" may work.
- In `updateHasDataLinks` and `updateHasPreregLinks`, we no longer reset `dataLinks`, `preregLinks` and `preregLinkInfo` because the backend doesn't like `null` for those fields.
- It was suggested that we set `dataLinks` and `preregLinks` to empty arrays, which the …
> [ENG-1864][ENG-1838] Add helpful error messages when url is invalid. Fix remove save error.

- app/controllers/content/index.js
- app/templates/content/index.hbs
- config/environment.js
- package.json
- yarn.lock
~# NOT YET READY FOR MERGE~
~This needs https://github.com/CenterForOpenScience/ember-osf/pull/450 to be merged and released first.  Then the yarn deps can be updated to replace the second commit.~
Stop logging unused events to keen.  No point in wasting bandwidth for stuff we don't use.
No visible effects.  Stop sending `non-contributor-preprint-downloads` to Keen but continue to send them to GA.  Logging stub function has been left in in case we want to tee these events again later.
Will be dev-tested after release.
https://openscience.atlassian.net/browse/ENG-2010
> [WIP][hotfix][ENG-1964] stop unnecessary keen logging

- app/templates/components/multiple-textbox-input.hbs
- Add a data-test attribute so Selenium test can grab HTML elements reliably in testing
- The multiple-text-input used for data availability and prereg links did not have a data-test attr in the previous version. This fix will add the data-test attr (`data-test-multiple-textbox-index={{index}}`) to the wrapping div, so the text input should be accessible by looking for the `<input>` element within this div (the input being used does not allow for data-test attrs to be put on it directly, so this workaround is needed)
Please let me know if the text-box is gettable and if any other changes are needed!
https://openscience.atlassian.net/browse/ENG-2057
- the ember {{input}} helper does not want to take the `data-test` attrs, so this workaround was done instead. Using vanilla HTML `<input>` …
> [ENG-2057]Add data-test attr to multi-text input wrapping div

- app/controllers/submit.js
- app/mixins/setup-submit-controller.js
Providers that don't allow submissions are shown on the submit page, and that's not right.
- changed `controller/submit.js` to filter on `allow_submissions` when getting the preprint providers
- changed the `findAll` to use `query` instead
- ~~Side effect: the URL for getting the preprint providers has the `filter[allow_submissions]=true` in there twice. Less than ideal, but is taking far too long to debug the issue, so am leaving it be for now. Sorry.~~
Please verify that only providers that have `allow_submissions=true` are shown on the submit page. this should still include OSF
`NA`
`NA`
> [Hotfix] Only show providers that allow submissions on submit page

- app/templates/components/author-assertions.hbs
The `Preregistration` section content not looking at the correct attribute on the preprint.
> [HOTFIX] Author assertion dropdown content.

- app/templates/content/index.hbs
- show a user's full name for preprints detail page to keep the displayed name consistent across preprints pages
- show user's `fullName` instead of `user.name` which will only show given name and family name
- Please note that whatever name is entered in a user settings "Full name" will be shown in the preprints detail page. A middle name entered in the "Middle name" field will not be shown.
https://openscience.atlassian.net/browse/ENG-1120
> [ENG-1120] Show users full name (including middle name) for preprints detail page

- app/components/preprint-form-authors.js
- app/locales/en/translations.js
- Update the toast message shown when trying to add a user marked as spam.
- Removed a condition that would only show the API error message if users were trying to add a contributor that was already on the preprint. This should allow for the specific API error message to be shown in all cases, unless the API error does not come with a `detail` field.
- When adding users by Email, please check that an email that is marked as spam in the admin app will result in a meaningful toast error. Previously it told the user to "Try again," but now it should be a bit more informative.
- Another condition to double check would be when trying to add an email that is already associated with the preprint (ie: user with email address abc@xyz.com is already a contributor, and I try to add a contributor by …
> [ENG-2801] Show request error message for failed contributor adds

- app/styles/app.scss
- app/templates/components/search-facet-taxonomy.hbs
- Make the preprints subjects filtering interface more accessible
- use `<button>` instead of `<span role="button">` for the subjects expand/collapse carets
- add necessary styling
- If you are using a screenreader, users should be able to tab into those expand/collapse carets and the screenreader should dictate what subject the user is going to expand/collapse
https://openscience.atlassian.net/browse/ENG-2946
> [ENG-2946] Make search-facets more accessible

- app/templates/content/index.hbs
- package.json
- yarn.lock
Fix some more accessibility problems on the preprint detail page
1. Update version of ember-osf to fix sharing icons not having aria-labels
2. Remove redundant `id='view-page'`
3. Add expand/collapse aria label to mfr expand/collapse control
https://openscience.atlassian.net/browse/ENG-3009
https://openscience.atlassian.net/browse/ENG-2977
This will need to be yarn updated and ci run after https://github.com/CenterForOpenScience/ember-osf/pull/456 is deployed. Also, this does not fix the MFR iframe issue, which looks to be an MFR problem.
> [ENG-3009][ENG-2977] Fix a11y problems on preprint detail page

- app/templates/content/index.hbs
Tags on a withdrawn preprint did not have the same contrast as tags on a public preprint. This fixes that so that they both have enough contrast.
1. Ensured that the withdrawn tags were in the proper css class
This should be isolated to just the tags in the withdrawn section, so if they pass accessibility, it should be good.
https://openscience.atlassian.net/browse/ENG-3344
> [ENG-3344] Ensure withdrawn tags have contrast override

- app/controllers/submit.js
- Stop allowing users to enter 20 white spaces to bypass validation for Abstract section
- use `ignoreBlank` when validating the Abstract so users cannot just enter white space when revising a preprint (validation cannot be bypassed like this for the initial submission)
- Abstract section of osf.io/<preprint_guid>/edit no longer allows only-whitespace
- Please verify that preprint submission (osf.io/preprints/submit/) and preprint updating (osf.io/<preprint_guid>/edit) workflows do not allow users to enter a blank or all-whitespace Abstract in the Basics section
https://openscience.atlassian.net/browse/ENG-3482
> [ENG-3482] Don't allow pure whitespace in abstract

- app/locales/en/translations.js
- app/routes/content.js
- app/routes/content/index.js
- app/templates/content/index.hbs
- Use impact metrics to show preprint view count
- Switch download count to use impact download count as opposed to the `preprint.primaryFile.extra.downloads`
- *Will need related ember-osf repo change to work*
- Added Views to preprint overview page
- Updated download count to be read from the impact metrics, as opposed to the `preprint.primaryFile.downloadCount`
- Reworded "Download preprint" to just say "Download" to avoid a display issue where the text is forced beneath onto the line below. (currently the highest viewed preprint has 187k views, most downloaded has 532k downloads)
- without shortened label
- with shortened label
https://openscience.atlassian.net/browse/ENG-23
- I've opted to serialize the request metadata into an `apiMeta` attribute, similar to how we handle …
> [ENG-23] Show preprint view count

- app/components/author-assertions.js
- app/controllers/submit.js
- app/templates/components/preprint-form-header.hbs
- app/templates/submit.hbs
- tests/unit/controllers/submit-test.js
Remove unnecessary sloan flags from codebase, because clean code is happy code.
1. Simplify computeds relying on sloan flags
2. Remove if statements in templates relying on sloan flags
3. Fix test
The whole sloan process from adding information to showing it on the preprint could be affected. Will need to be verified with all the sloan flags and switches turned off once the backend supports it.
https://openscience.atlassian.net/browse/ENG-3016
> [ENG-3016] Remove reliance on sloan flags and switches

- app/controllers/content/index.js
- app/locales/en/translations.js
- app/templates/content/index.hbs
- config/environment.js
- Our metrics are looking a little fishy (suspiciously high download counts relative to view count for preprints submitted before 2019), so the API will only return trusty-worthy metrics from 2019 onward. Some preprints may have their numbers skewed because of this, so we will add a hover-text to indicate the dates that these metrics cover
- Add hover text to download/view count on preprint detail
- Add new config `config.OSF.metricsStartDate` for start dates
When hovering the preprints view/download, there should be a disclaimer about the metrics
https://openscience.atlassian.net/browse/ENG-3677
There is a backend piece that will adjust the metrics to use only the metrics after 2019 (when metrics data may have gotten out of sync) here: …
> [ENG-3677] Add disclaimer to preprints metrics

- app/controllers/submit.js
- app/templates/submit.hbs
- package.json
- tests/unit/controllers/submit-test.js
- Show/Hide Assertions/COI panels in submit page based on a preprint-provider flag (`assertions_enabled`)
- Add `assertionsEnabled` flag to `submit` page controller
- controls which panels are visible (hide COI and Assertions based on this flag)
- controls which validations occur
- controls which validation errors are shown
- Is based pretty heavily on un-doing a [prior PR](https://github.com/CenterForOpenScience/ember-osf-preprints/pull/732) to remove the reliance on sloan feature-flags
- Will need to toggle the `assertions_enabled` flag on the preprint_provider page in the admin app
- The `assertions_enabled` does not control whether we show/hide COI and/or Author Assertions on the preprint-detail page (e.g. osf.io/preprints/<provider-id>/<preprint-id>), so if a preprint is submitted …
> [ENG-4460] Toggle assertions based on preprint-provider flag

- app/components/taxonomy-top-list.js
- app/routes/index.js
- app/templates/components/taxonomy-top-list.hbs
- Update query-params for links going to preprint discover page
- Update query-params for landing page search textbox
- Update query-params for landing page "Browse by subjects" links (`taxonomy-top-list`)
- No need to update `additional-provider-list`, as we will be dropping livedata preprint-provider and that's the only provider on Production that seems to have `additional_provider`
> Update taxonomy-top-list qp

- app/locales/en/translations.js
- app/templates/submit.hbs
- Add info text about our moderation policy to users submitting to OSF Preprints
- Add translation text
- show text if users are submitting to OSF Preprints
- On the preprints/submit page:
- OSF Preprints should have its `reviews_workflow` changed to `post-moderation` in the admin app
- Message "You can read more about [OSF Preprints moderation policies](https://help.osf.io/article/592-preprint-moderation)..." should only show up for users submitting to OSF Preprints
- Help link currently goes to a "Page not found", but will be made public upon release.
- Message should show/hide when users select OSF Preprints or a different provider in the "Select a service" panel in preprints/submit page. The message won't update until "Save and continue" is pressed …
> [ENG-4907] Add moderation message to OSF Preprints
