- app/components/preprint-form-subjects.js
- app/styles/app.scss
- app/templates/components/preprint-form-subjects.hbs
> Build Subject Selection in Add/Edit page [PREP-80]

- app/controllers/add-preprint.js
- app/controllers/browse.js
- ember-cli-build.js
- mirage/config.js
- mirage/factories/preprint.js
- package.json
Syntax changes to satisfy failing unit tests. Should be useful to address common failures, now that travis CI is running for all. (as of #15)
Make automatic syntax checking tool happy.
> Appease linters (to get CI passing for all)

- app/components/taxonomy-tree.js
- app/controllers/discover.js
- app/templates/components/taxonomy-tree.hbs
- app/templates/discover.hbs
Add the provider filter to the discover page. Also uses subject and provider filters to update search when those are added or removed.
> Provider support for discover page

- app/components/taxonomy-tree.js
- app/controllers/discover.js
- app/helpers/if-filter.js
- app/templates/components/taxonomy-tree.hbs
- app/templates/discover.hbs
This adds checkboxes to select filters, and should fix tree.
> Checkboxes and fixes

- app/controllers/preprints/view.js
- app/styles/app.scss
- app/templates/components/supplementary-file-browser.hbs
- app/templates/preprints/view.hbs
- tests/unit/controllers/preprints/view-test.js
Extend MFR & collapse details on view page.
https://openscience.atlassian.net/browse/PREP-114
> Feature/Extend MFR & collapse details on view page

- README.md
How-to generate fake preprints with multiple providers, and update the provider model, both OSF side!
> Add notes about running OSF scripts to generate data

- app/routes/submit.js
In the submit page project selector, only show nodes that the user could actually turn into a preprint.
Exclude:
- Things that are already preprints
- Projects where the user does not have admin privileges
Change what shows up in the "select a project" dropdown box.
In this version, we filter permissions client side. This is a hack in the interests of time.
The API does not currently support [filtering](https://github.com/abought/osf.io/blob/9cf7f7d1b3f0c5e933eedf82c3e1ba388579b3f4/api/nodes/serializers.py#L54-L54) on current_user_permissions.
Adding a new filter would be good, but is not trivial under current timeline. SerializerMethodField does [not](https://github.com/abought/osf.io/blob/c3d39a3d07ad38cdebaac9280cb928e67179bb59/api/base/filters.py#L132-L132) support the `contains` …
> Submit page project selector: restrict to relevant items

- app/styles/app.scss
- app/templates/page-not-found.hbs
Basic styling to this page, remove reference to some cat
> Add style to not found page

- app/styles/app.scss
- app/templates/components/file-uploader.hbs
- app/templates/components/preprint-form-project-select.hbs
- app/templates/submit.hbs
This is a first pass, more nuances will follow but overall design won't change significantly.
> Adding style to upload section

- app/styles/app.scss
Minor css fixes to have header images resize to fit the width of viewport
> Fix header sizing on large monitors

- app/routes/index.js
- app/templates/index.hbs
As per discussion with product and co, remove "hosted" count and format SHARE preprint count with commas to make it readable!
> Remove our count, format SHARE count with commas

- app/controllers/discover.js
- app/styles/app.scss
- app/templates/components/preprint-form-header.hbs
Fixes to the preview sections, making things compact, improving colors and typography. Adding proper tags for content
> Add fixes for Dawn's changes

- app/components/confirm-restart-submit-preprint.js
- app/components/file-uploader.js
- app/controllers/submit.js
- app/routes/content.js
- app/routes/submit.js
- app/templates/components/confirm-restart-submit-preprint.hbs
- app/templates/components/file-uploader.hbs
- app/templates/submit.hbs
> [WIP] Feature/Submit Form Polishing III

- app/components/preprint-form-authors.js
- app/components/unregistered-contributor-form.js
- app/controllers/submit.js
- app/helpers/contributor-is-current-user.js
- app/helpers/permission-to-remove-contributor.js
- app/routes/submit.js
- app/styles/app.scss
- app/templates/components/preprint-form-authors.hbs
- app/templates/components/preprint-form-header.hbs
- tests/unit/helpers/contributor-is-current-user-test.js
- tests/unit/helpers/permission-to-remove-contributor-test.js
> [WIP] Feature/Submit Form Polishing IV

- app/mixins/reset-scroll.js
- app/routes/content.js
- tests/unit/mixins/reset-scroll-test.js
> Feature/Submit Form Polishing V

- app/styles/app.scss
- app/styles/authors.scss
- app/templates/components/preprint-form-authors.hbs
> Feature/More Preprint Changes

- app/templates/content.hbs
Download count for current file wooooooo
> Use dwnload count now in file serializer next to download button for current file

- app/styles/app.scss
- app/templates/index.hbs
Addressing: 
https://trello.com/c/05NMRvpq 
https://trello.com/c/PWgt9cN3
I'll need to look at the advisory layer with morning light tomorrow, if I change anything I'll send a new PR.
> Style tickets 

- app/models/taxonomy.js
> Fix syntax in taxonomy model

- app/controllers/content.js
- app/templates/content.hbs
https://trello.com/c/rHaSnYpJ/79-non-bibliographic-contributors-are-still-listed-under-authors-on-preprint-page
https://trello.com/c/yFbLgjzN/133-view-page-not-all-authors-appearing-on-author-list
> Feature/Contributors issues on Preprint View

- app/components/taxonomy-top-list.js
- app/templates/components/taxonomy-top-list.hbs
https://trello.com/c/0WrR1Nc2/19-show-tooltip-examples-of-5-subdisciplines-on-hover-of-category
> Add tooltips to subjects

- app/components/search-result.js
- tests/integration/components/search-result-test.js
Fix CI failure reported by @caneruguz in #131, which also affected develop branch.
> Fix CI failure due to missing thing the component needs to render

- app/components/file-uploader.js
- app/components/search-result.js
- app/templates/components/file-uploader.hbs
Include hotfixes to master that missed develop into current develop and resolve merge conflict
> Sync develop with master 

- app/routes/404.js
- app/routes/content.js
- app/templates/404.hbs
Continuation of #113, instructions on testing and wanted behavior are included in Erin's PR.
> Continuation of 113

- app/controllers/content.js
Use encodeURIComponent properly.
> fix linkedin and facebook

- app/templates/components/unregistered-contributor-form.hbs
removes quotes for disabled attribute
> Remove quotes to (fixes form validation)

- app/controllers/discover.js
- app/helpers/filter-replace.js
Add a white list of providers that can be used as a filter. Also add filter for OSF -> OSF Preprints, Research Papers in Economics -> RePEc
> Add whitelist and put new name for research paper in economics [PREP-162] 

- app/routes/application.js
- app/templates/components/preprint-form-authors.hbs
* Fix bug when changing browser language preferences to ensure that the change is only applied if the language is available in the locales (supposed to default to English if the browser's preferred language is not present).
* Fix references in popovers.
> Feature/i18n fixes [PREP-182]

- app/templates/components/convert-or-copy-project.hbs
Fixes minor issues QA came up with as noted here: https://openscience.atlassian.net/browse/PREP-203
> Fix buttons for confirming component selection [PREP-203]

- app/components/taxonomy-top-list.js
change to Unites StateS
https://openscience.atlassian.net/browse/PREP-204
> Fix typo in Law [PREP-204]

- app/controllers/discover.js
- app/templates/discover.hbs
See [Jira Comment](https://openscience.atlassian.net/browse/PREP-178?focusedCommentId=39629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-39629)
Basically, just including document counts
> Add document counts next to providers [PREP-178]

- app/templates/head.hbs
> [Hotfix] Add title back in document head [PREP-238]

- app/components/file-uploader.js
- app/controllers/submit.js
- app/templates/components/preprint-form-header.hbs
- app/templates/content.hbs
- app/templates/submit.hbs
Issues found by QA for Edit Preprints
https://openscience.atlassian.net/browse/PREP-137
- Collapsed state shows file version
- If user uploads unchanged version of paper, on 'Save and continue' version will revert back to proper version.
- DOI can be submitted as either the DOI or the DOI link
- If inputting a DOI link, when the input box loses focus, the displayed input will be stripped to just the DOI itself.
- Restore handling of orphans just in case old orphan slips through.
> Feature/Edit Preprint Improvements [PREP-137] 

- app/locales/en/translations.js
https://openscience.atlassian.net/browse/PREP-237
Language updates around deleting preprints.
> Feature/Language changes around deleting preprints [PREP-237]

- app/components/taxonomy-top-list.js
One-line fix to add the tooltip for Engineering
> Fix Engineering tooltip [PREP-264]

- app/components/author-link/component.js
- app/components/author-link/template.hbs
- app/components/search-result.js
- app/controllers/discover.js
- app/controllers/index.js
- app/templates/components/search-result.hbs
- config/environment.js
Purpose
---------
Get preprints with non-bibliographic contributors to update SHARE properly
Ticket
------
https://openscience.atlassian.net/browse/PREP-269
> Update to support the latest SHARE format [PREP-269]

- config/environment.js
Build bug #216 regression (seems to be an ember cli build bug)
> Update ember build env (bug)

- app/controllers/discover.js
Makes whitelist for Providers case insensitive
https://openscience.atlassian.net/browse/PREP-279
> Case insensitive providers whitelist [PREP-279]

- app/routes/content.js
Add google scholar and more meta tags
https://openscience.atlassian.net/browse/PREP-295
> [PREP-295] Add google scholar and more meta tags

- app/controllers/submit.js
Fix licenseChanged behavior to be more accurate.
Fix inconsistencies on copyrightHolders
> [PREP-278] Fix inconsistensies on copyrightHolders

- package.json
There's at least one new PR merged to ember osf that is needed for the current release, so we need to update the current version for QA to be able to test.
Upgrade ember-osf version.
https://openscience.atlassian.net/browse/PREP-301
> Feature/Upgrade Ember-OSF version [PREP-301]

- app/routes/content.js
Reverts CenterForOpenScience/ember-preprints#237
> Revert "[PREP-295] Add google scholar and more meta tags"

- app/routes/content.js
https://openscience.atlassian.net/browse/PREP-300
Create a new preprint, logout, then try to access that url. It should work correctly now.
> Fix for GUID URL infinite redirects [PREP-300]

- app/routes/content.js
401, 403, and 404 were causing the page to break
Handles API errors in content route and transitions to the appropriate page
N/A
https://openscience.atlassian.net/browse/EOSF-179
> [hotfix] [EOSF-179] Handle API errors

- config/environment.js
Sets defaults for environment variables if they are not present
Changes to config only
https://openscience.atlassian.net/browse/EOSF-443
> [EOSF-443] Add defaults for missing environment variables

- app/templates/content.hbs
Image caret persists even though metadata is stacked.
Hide caret on sm and xs screens.
https://openscience.atlassian.net/browse/PREP-202
> Feature/Hide Caret on XS/SM Screens [PREP-202]

- app/styles/brands/psyarxiv.scss
- app/templates/index.hbs
https://openscience.atlassian.net/browse/EOSF-473
Update PsyArxiv colors
Now looks like this:
> [EOSF-473] Update PsyArxiv colors

- app/router.js
- app/services/theme.js
- tests/unit/controllers/application-test.js
- tests/unit/controllers/content-test.js
- tests/unit/controllers/index-test.js
- tests/unit/controllers/submit-test.js
- tests/unit/routes/application-test.js
- tests/unit/routes/content-test.js
- tests/unit/routes/discover-test.js
- tests/unit/routes/forbidden-test.js
- tests/unit/routes/index-test.js
- tests/unit/routes/page-not-found-test.js
- tests/unit/routes/resource-deleted-test.js
Fixes logout redirects to go back to the correct page
Updates the redirect url on the theme service based on the current window location after the route has transitioned and rendered
N/A
https://openscience.atlassian.net/browse/EOSF-239
> [EOSF-239] Update logout with current location after each transition

- app/locales/en/translations.js
- config/environment.js
- tests/unit/services/theme-test.js
https://openscience.atlassian.net/browse/EOSF-487
Add Permission language for -rxiv in agrixiv page and keep Sciello from showing an error
> [EOSF-487] add permission language to agrixiv

- app/components/search-result.js
- app/templates/components/search-result.hbs
https://openscience.atlassian.net/browse/EOSF-172
Restricts the amount of authors shown under preprints search to 10 per preprint.
Instead of looping through the original collection, loops through a new ember function that pre-filters the collection and restricts the amount returned to 10.
> [EOSF-172] Truncate author list if it will exceed 2 lines

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF- 
Updates ember-osf to the latest develop commit hash
> Update ember-osf commit

- app/styles/brands/scielo.scss
https://openscience.atlassian.net/browse/EOSF-238
Change share logo to white for Scielo
> [EOSF-238] Change share logo to white for Scielo

- app/components/supplementary-file-browser.js
- app/controllers/content.js
- app/templates/content.hbs
https://openscience.atlassian.net/browse/EOSF-549
Allows passing in query param on content page that pre-selects a file to display if the id passed matches that of a file in the preprint
> [EOSF-549] Add query param for selected file on content page

- app/styles/app.scss
- app/templates/components/file-uploader.hbs
- app/templates/components/preprint-form-project-select.hbs
https://openscience.atlassian.net/browse/EOSF-547 
One or two letters on the right and the left of the paragraph are cut off. Doesn't matter what browser window width you are viewing with.
There is a need to a fix the text.
Changed text style
> Fix Preprints submit form, create component, text [EOSF-547]

- app/templates/index.hbs
https://openscience.atlassian.net/browse/EOSF-518
Remove Simine Vazire and add Benjamin Brown : PsyArXiv, Georgia Gwinnett College.
Update index.hbs template file.
> Update advisory board [EOSF-518]

- app/components/maintenance-banner/component.js
- app/components/maintenance-banner/template.hbs
- app/styles/app.scss
- app/styles/brands/_brand.scss
- app/templates/application.hbs
https://openscience.atlassian.net/browse/EOSF-585
Add maintenance banner to preprints
Added a component. This is temporary and will be moved into ember-osf.
> [EOSF-585] Hotfix/maintentance banner

- scripts/add-domains.js
https://openscience.atlassian.net/browse/EOSF-597
Code linting errors as a result of recent merges
Add eslint config for add-domains script
> [EOSF-597] Add lint config to add-domains script

- package.json
- yarn.lock
Switch from the commit to the just-released version
> Update to ember-osf 0.4.0

- app/routes/content/index.js
- ember-cli-build.js
> [hotfix] Change render to export and format=pdf, fix babel warning message

- app/styles/brands/lawarxiv.scss
https://openscience.atlassian.net/browse/EOSF-607
Change theme color #5 to white for better contrast in auth dropdown.
Before
After
> Hotfix/LawArXiv Color Improvement [EOSF-607]

- app/controllers/content/index.js
- app/routes/content/index.js
❗️Needs CenterForOpenScience/osf.io#7139
https://openscience.atlassian.net/browse/EOSF-614
Required URL changes for Google Scholar
Updates the URLs for the "Download Preprint" button and the `citation_pdf_url` meta tag
Notes for QA/testing:
1. Create a new preprint or go to an existing one
1. Verify that the Download Preprint button still works as expected (should download the file in its native format)
1. Go the meta tags (will need Dev Tools open), copy the URL from `citation_pdf_url` and paste it in a new tab. The file should be downloaded as a pdf.
> [EOSF-614] URLs for Google Scholar

- package.json
- yarn.lock
N/A 
Update to use latest ember-osf commit
Updated package.json to use latest commit for ember-osf and regenerated yarn.lock
N/A
> Use latest ember-osf commit

- package.json
- yarn.lock
N/A
Update ember-osf to latest commit in develop.
Updated commit hash in package.json and regenerated yarn.lock.
Licenses should now populate in submit.
> Updated to ember-osf commit hash to latest commit on develop

- app/templates/content/index.hbs
> remove .content

- app/styles/app.scss
- config/environment.js
> [WIP] New providers config

- package.json
- yarn.lock
N/A 
Update to latest pre-0.5.0 ember-osf
Updated commit hash to tip of ember-osf develop
???
> Updated ember-osf to latest pre-0.5.0 commit

- package.json
- yarn.lock
N/A
Pin to ember-osf 0.5.0
1. Pinned to ember-osf 0.5.0 in package.json
1. Updated yarn.lock
None
> Pin to ember-osf 0.5.0

- README.md
- app/router.js
- app/routes/content/edit.js
- app/routes/content/index.js
- app/routes/provider.js
- app/services/theme.js
- app/utils/get-redirect-url.js
- config/environment.js
- ember-cli-build.js
- scripts/add-domains.js
- tests/unit/utils/get-redirect-url-test.js
Reverts CenterForOpenScience/ember-preprints#342
> Revert "[EOSF-623] domain redirects"

- config/environment.js
No longer needs suffix for logo sharing assets
> No longer needs suffix for logo sharing assets

- config/environment.js
> Point assets to https

- config/environment.js
https://openscience.atlassian.net/browse/EOSF-693
Adding thesiscommons and sportrxiv to config files this allows their branded services to be created
Adding thesiscommons and sportrxiv to config files
None
> Feature/Add Thesiscommons and Sportrxiv to Config Files [EOSF-693]

- .travis.yml
- testem.js
N/A
Use headless Chrome for tests
Added chrome:stable addon for Travis and configure testem to use headless Chrome
N/A
> Use headless Chrome for tests

- app/templates/components/error-page.hbs
- app/templates/components/preprint-navbar-branded.hbs
Reverts CenterForOpenScience/ember-preprints#335
> Revert "Preprints Branded Not Found Page Broken Link [EOSF-621]"

- app/templates/content/index.hbs
https://openscience.atlassian.net/browse/EOSF-697
Make author and DOI links actually navigate when clicked.
Added missing onclick=
None
> [EOSF-697] Added missing onclick= for click actions

- app/routes/content/index.js
- tests/unit/routes/index-test.js
https://openscience.atlassian.net/browse/EOSF-666
Google Scholar meta tags were displaying the wrong first/last names for some unregistered contributors.
A conditional was used to determine which name is used for the Google Scholar meta tags.  If the user being displayed is an unregistered contributor, the first/last name tags will use parts of the unregistered contributor field.
The issue before was that for certain unregistered contributors their name would not show up properly.  So for example:
<br>
What was happening is that the unregistered contributor was using an email that is already in use.  Therefore, it was using the first/last name of the previous contributor.  After the fix, unregistered contributors who are using the same emails as other users show the right name:
This issue …
> [EOSF-666] Fix Google Scholar missing authors

- README.md
N/A
Update README with instructions for using local preprint provider assets
Updated README.md
N/A
> Updated README with instructions for using local preprint provider assets

- app/templates/content/index.hbs
Reverts CenterForOpenScience/ember-preprints#379
> Revert "[EOSF-697] Added missing onclick= for click actions"

- app/components/provider-carousel.js
- tests/integration/components/provider-carousel-test.js
https://openscience.atlassian.net/browse/EOSF-680
Special case provider carousel to pull out ASU.
> Feature/Pull ASU out of Provider Carousel [EOSF-680]

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-680
Point to latest ember-osf commit that has the SHARE url changes
> Feature/Update Ember-OSF commit [EOSF-680]

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-733
Update to latest ember-osf.
Update package.json to latest ember-osf commit and rebuild yarn.lock.
None
> [EOSF-733] Update to latest ember-osf

- package.json
- yarn.lock
N/A
Update to use latest ember-osf.
Updated package.json and rebuilt lockfile.
N/A
> Update to use latest ember-osf

- app/controllers/submit.js
https://openscience.atlassian.net/browse/EOSF-631
Simultaneous saving of the node and preprints was causing the peer-reviewed publication DOI to not be saved.
Changed saveBasics code to only attempt to save the preprint after the node has been saved. 
Saving the basics section may be slightly slower because it has to wait for the node to save before attempting to save the preprint.
Make sure all values from the basics section are properly saved, but especially the peer-reviewed article DOI.
> [EOSF-631] Refactored saveBasics to save node, then model, synchronously

- yarn.lock
N/A
Freshen yarn.lock
Ran yarn upgrade
N/A
> Freshen yarn.lock

- package.json
N/A
Update use-ember-osf-develop npm script to use @centerforopenscience NPM org scope.
Added @centerforopenscience/ prefix to ember-osf in use-ember-osf-develop.
N/A
> Update use-ember-osf-develop with org scope

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-694
Use latest ember-osf from develop
Update ember-osf in package.json and yarn.lock
None
> Use latest ember-osf develop [EOSF-694]

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-786
Update to use latest ember-osf develop
Updated package.json and regenerated yarn.lock
N/A
> [EOSF-786] Use latest ember-osf develop

- app/locales/en/translations.js
- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-655
Add missing preprint word substitutions and update ember-osf.
* Add missing preprint word substitutions
* update ember-osf
?
> Hotfix/0.111.13 [EOSF-655]

- app/index.html
Related to https://openscience.atlassian.net/browse/OSF-8382
Speed up blocking request for font.
There should not be any. I've verified with @caneruguz that this weight is unnecessary, and 700 is already removed in the OSF.
> Remove unneeded font weight

- config/environment.js
https://openscience.atlassian.net/browse/EOSF-815
Add medarxiv to the whitelist
Added medarxiv to the whitelist
None
> Added medarxiv to the whitelist

- config/environment.js
https://openscience.atlassian.net/browse/EOSF-817
Add experimentalprotocols to whitelist
Added experimentalprotocols to whitelist
None
> Added experimentalprotocols to whitelist

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-771
Use latest ember-osf develop
Use ember-osf@develop
None
> Use ember-osf@develop [EOSF-771]

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-758
Update preprints for updated ember-osf
Updates to yarn and package.json files.
> [EOSF-758] Update preprints for recent ember-osf

- package.json
- yarn.lock
https://openscience.atlassian.net/browse/EOSF-735
Update to latest osf-style which includes fixes to accommodate gravatar image in nav bar
`yarn upgrade @centerforopenscience/osf-style@1.5.1`
None
> [EOSF-736] Update to osf-style@1.5.1

- app/components/preprint-status-banner/component.js
https://openscience.atlassian.net/browse/MOD-84
https://openscience.atlassian.net/browse/MOD-123
Handle displaying preprints that have no actions.
Also, drive-by fix the bug that sometimes didn't display the provider name in the preprint status banner.
If a preprint has no actions, don't display the comment dropdown in the status banner.
None.
> [MOD-84][MOD-123] Handle preprints with no actions

- app/controllers/content/index.js
- app/templates/content/index.hbs
https://openscience.atlassian.net/browse/MOD-138 
Show status banner to all contributors.
There is a bit of a delay before the status bar shows up for non-admin contributors.
> [MOD-138][Improvement] Show status banner to contributors

- app/locales/en/translations.js
https://openscience.atlassian.net/browse/MOD-143 
Make language more clear.
Update status explanation in status banner and in feedback dropdown.
> [MOD-143][Improvement] Update wording on status banner to make more clear

- app/controllers/submit.js
https://openscience.atlassian.net/browse/MOD-158
Show "pending" banner after resubmission.
Refresh the model on resubmit.
None
> [MOD-158][Fix] Refresh model after resubmission

- app/locales/en/translations.js
https://openscience.atlassian.net/browse/MOD-164
Fix typos in submission form.
None
> [MOD-164][Fix] Fix typos in submission form

- app/locales/en/translations.js
*Wording changes to the form are already in the CHANGELOG*
https://openscience.atlassian.net/browse/MOD-164
I missed a comma in #473 
Added a comma.
None
> [MOD-164][Fix] Add missing comma

- .travis.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile-alpine
- README.md
- package.json
- testem.js
- tests/integration/components/provider-carousel-test.js
- tests/integration/components/search-facet-taxonomy-test.js
N/A
DevOps requirements
* Update README
* Update travis config
* Add headless Firefox
Had to skip two tests for Firefox, but put a ticket in the backlog: https://openscience.atlassian.net/browse/EOSF-886
> Add headless firefox and some other updates

- CHANGELOG.md
- app/styles/app.scss
- package.json
- yarn.lock
Footer styling has been added to ember-osf.  Redundant code should be removed from preprints and registries.
Remove footer styling from ember-osf
https://openscience.atlassian.net/browse/EOSF-913
> [EOSF-913] Remove footer styling

- package.json
- yarn.lock
To update to the latest version of ember-osf
https://openscience.atlassian.net/browse/EOSF-931
> [EOSF-931] Update to latest ember-osf

- CHANGELOG.md
- app/templates/index.hbs
To show the donate banner on branded preprints
Remove conditional so that the banner shows up regardless of branded/unbranded
https://openscience.atlassian.net/browse/EOSF-953
> [EOSF-953] Show donate banner on branded preprints

- CHANGELOG.md
- app/locales/en/translations.js
- app/templates/content/index.hbs
This reverts commit 3bf716c397e14b2a790638b9bac3953044cab82c.
> Revert "[Improvement][MOD-159] Add DOI message - Preprints (#475)"

- package.json
- yarn.lock
Fix dropzone file upload on Preprint submit
Update to latest ember-osf@develop, which fixes this issue.
File uploads should work again
N/A
> Update ember-osf to develop to fix dropzone upload issue

- CHANGELOG.md
- app/components/preprint-form-authors.js
- package.json
- yarn.lock
Update renamed `meta.total`
Updated `meta.total` to `meta.total_pages` in preprint-form-authors component
Make sure authors section of Preprint submit/edit still works properly.
https://openscience.atlassian.net/browse/EOSF-960
> [EOSF-960] Update meta.total to meta.total_pages

- app/controllers/submit.js
We missed a spot...
Rename for `submitAction`.
https://openscience.atlassian.net/browse/EOSF-885
> [EOSF-885] review action rename for submitAction

- CHANGELOG.md
- app/controllers/submit.js
- app/locales/en/translations.js
- app/routes/content/edit.js
- app/routes/submit.js
- package.json
- yarn.lock
When leaving the submit/edit page, there should be a warning to stop users from leaving if there are unsaved changes.  The purpose of this PR is to add a dialogue box that pops up when the user tries to leave or refresh the page in the case that there are unsaved changes.
- Added `ember-onbeforeunload` to handle transition checks on the submit and edit routes
- Re-implemented the `disciplineChanged` computed function, which checks if there have been user changes on the discipline list.
- Added a `computed` function to check the changed fields (`uploadChanged`, `basicsChanged` and `disciplineChanged`).  The `computed` is used to determine whether or not the page is dirty and if the dialogue box will show on redirect.
https://openscience.atlassian.net/browse/EOSF-783
> [EOSF-783] Warning when leaving submission/edit page

- app/controllers/submit.js
We missed another line...
Rename 'action' to 'review-action' for the `resubmit` fuction.
None
https://openscience.atlassian.net/browse/EOSF-885
> [EOSF-885]Rename review action for resubmit

- CHANGELOG.md
Add changelog.
Add changelog.
https://openscience.atlassian.net/browse/EOSF-839
> [EOSF-839] Add CHANGELOG

- CHANGELOG.md
- app/components/preprint-form-authors.js
- app/components/search-facet-taxonomy.js
- app/components/subject-picker/component.js
- app/mixins/setup-submit-controller.js
- app/routes/index.js
- package.json
- tests/integration/components/search-facet-taxonomy-test.js
- tests/integration/components/supplementary-file-browser-test.js
- tests/unit/controllers/content/index-test.js
- tests/unit/controllers/submit-test.js
- yarn.lock
Update Preprints to use model.queryHasMany instead of model.query
* Use latest ember-osf
* Modify tests so they are compatible with queryHasMany
* Use model.queryHasMany everywhere model.query is used
* Get pagination info directly from meta in preprint-form-authors component
Full regression recommended.
N/A
> use queryHasMany

- config/environment.js
- ember-cli-build.js
Update raven, add releases
config changes,
No QA needed
> Update ravenjs to 3.22.1, add releases configuration

- app/controllers/submit.js
- app/locales/en/translations.js
Fix capitalization problem for "original publication date" display on:
1. Submission/edit page
2. Preprint detail page
3. Validation error message
See abobe.
Make sure capitalization error for the pages are fixed.
https://openscience.atlassian.net/browse/IN-78
> [IN-78][Preprints] Fix capitalization problem

- app/controllers/submit.js
- app/routes/submit.js
- tests/unit/controllers/submit-test.js
Update the logic for the warning message on the submit page.
Use code changes from #535
Make sure it works in all cases
https://openscience.atlassian.net/browse/IN-175
> [IN-175][Preprints] Update logic for submit warning message

- app/locales/en/translations.js
Add social information to helper/placeholder text in authors
select form during preprint creation.
Update help text
https://openscience.atlassian.net/browse/IN-102
> [IN-102][Preprints] Fix help text

- CHANGELOG.md
- app/components/preprint-form-header.js
- app/components/preprint-form-section.js
- app/components/provider-carousel.js
- app/components/subject-picker/component.js
- app/controllers/submit.js
- app/locales/en/translations.js
- app/locales/es-disabled/translations.js
- app/styles/app.scss
- app/templates/components/preprint-form-header.hbs
- app/templates/components/provider-carousel.hbs
- app/templates/submit.hbs
- tests/unit/controllers/submit-test.js
Choose preprint provider when creating an unbranded preprint.
* Modify provider-carousel component to support selection
* Modify preprint-form-header to add server chooser section
* Modify submit controller to add provider chooser
* Modify subject-picker component to take provider as a parameter
* Allow overriding of denyOpen message
* Use i18n for denyOpen message
* Adjust onbeforeunload warning logic
* Update submit controller unit test
Submission should work properly when starting from both unbranded and a branded provider.
https://openscience.atlassian.net/browse/IN-76
> [IN-76][Preprints] Choose preprint provider on create preprint

- app/controllers/submit.js
Fix issue where the node is not made public upon 
preprint submission.
In the submit controller save changes on the node model.
Follow-up to https://github.com/CenterForOpenScience/ember-osf-preprints/pull/526
[IN-97](https://openscience.atlassian.net/browse/IN-97)
> [IN-97][Preprints] Save node changes

- app/components/preprint-form-project-select.js
- app/templates/components/preprint-form-project-select.hbs
Fix the problem that the results stay in filtered state after the input lose focus.
Add `onBlur` and `onFocus` action.
None.
https://openscience.atlassian.net/browse/IN-77
> [IN-77][Preprints] Lazyloading quick fix.

- app/templates/components/preprint-form-header.hbs
Fix broken link to preprint provider in collapsed provider chooser panel.
Use provider-asset helper for preprint-form-header provider icon.
Should work now in all environments.
https://openscience.atlassian.net/browse/IN-201
> [IN-201][Preprints] Use provider-asset helper for preprint-form-header provider icon

- app/controllers/submit.js
Takes https://github.com/CenterForOpenScience/ember-osf-preprints/pull/561 and fixes eslint errors.
- Update to latest release/next-interfaces and fix merge conflicts
https://openscience.atlassian.net/browse/IN-271
> [IN-271][Preprints] Update preprint file relationship and eslint changes

- CHANGELOG.md
- app/routes/index.js
- app/services/theme.js
- package.json
- yarn.lock
Reduce # of preprints_provider calls
* Don't load providers on external domains
* Don't reload the provider in the theme
https://openscience.atlassian.net/browse/IN-192
> [IN-192][Preprints] Reduce # of preprints_provider calls

- CHANGELOG.md
- app/components/preprint-navbar-branded.js
- app/controllers/index.js
- app/controllers/submit.js
- app/locales/en/translations.js
- app/templates/components/preprint-navbar-branded.hbs
- app/templates/index.hbs
- app/templates/submit.hbs
- tests/integration/components/preprint-navbar-branded-test.js
Update the language on the preprint submission form and update the navbar to match.
- Update i18n translation
- Update submit controller and template
-----------
-----------
-----------
https://openscience.atlassian.net/browse/IN-117
> [IN-117][Preprints] Preprint submission language update

- CHANGELOG.md
- config/environment.js
- package.json
- yarn.lock
as part of GDPR compliance efforts, `anonymizeIp: true` allows
the sender IPs to be anonymized.
- Update config to set `anonymizeIp: true`
- Point to fork to allow setting GA configs.
In case GA is enabled on staging environments, you can verify this flag is set by looking at the GA requests in the console (filter by `collect`)
[IN-338](https://openscience.atlassian.net/browse/IN-338)
> [IN-338][Preprints] GA anonymize sender ip

- app/components/supplementary-file-browser.js
People shouldn't see commenting if not published or not public
Add check for published and public before rendering commenting
None known
https://openscience.atlassian.net/browse/IN-343
> [WIP][IN-343] Disallow hypothesis if node is private

- app/controllers/discover.js
- app/routes/discover.js
Botched a merge conflict fix.
Added back some nuked code
N/A
No Ticket 
Three PRs that collided badly:
[Fabmiz sentry](https://github.com/CenterForOpenScience/ember-osf-preprints/pull/563/files#diff-12da57c2f3df7dceed373bdacf2e27c5R20)
[Lauren livedata](https://github.com/CenterForOpenScience/ember-osf-preprints/commit/ac5a3aa97b62ce811f439a49ab0bf9f7df91e4c9#diff-12da57c2f3df7dceed373bdacf2e27c5R15)
[Yuhuai whitelist](https://github.com/CenterForOpenScience/ember-osf-preprints/pull/492/files#diff-12da57c2f3df7dceed373bdacf2e27c5R20)
> Fix discover page

- app/routes/content/edit.js
Edit page is broke because provider isn't set
Run setup for provider
NA
None
> [No Ticket][Preprints] Fix edit page

- app/controllers/submit.js
Moderated submission have invalid dates and no banner immediately after submission because the model isn't properly reloaded after saving the submit action.
Make the submit action chained with a then, reload the model
None known, check a few submission types to make sure they didn't break. Tested locally as many combos as I had available (pre/post/osf)
NA
> [NOTICKET][Preprints] Fix provider route transition

- app/templates/submit.hbs
[Fix] show description of selected provider in provider carousel on preprint submit page.
Don't rely on `theme.isProvider`
N/A
[IN-209](https://openscience.atlassian.net/browse/IN-209)
N/A
> [IN-209][Preprints] Fix show description of selected provider

- app/controllers/application.js
Add path to cookie banner so that it works on all parts of the OSF.
- Add `path=/` to cookie banner
Whenever a user accepts cookies on preprints, it should also carry over to all other parts of the OSF now
https://openscience.atlassian.net/browse/IN-324
`N/A`
> [IN-324][Preprints] Add path to cookie banner

- app/router.js
> [no ticket] fix edit

- app/components/chronos-submission-panel/component.js
- app/templates/content/index.hbs
Filter journals with APA as the publisher. Enable the widget only on PsyArxiv.
> [Chronos] Hardcode filter and enable only on PsyArxiv

- app/components/chronos-submission-panel/component.js
- config/environment.js
Store approved journal ids in config and make use of them in the filter.
https://openscience.atlassian.net/browse/Emb-414
> [EMB-414][Chronos][Preprints]store approved journal ids in config

- app/routes/content/index.js
Put contributors back to metatags.
When the user is not a prerender scraper, the `afterModel()` hook returns the promise for setting the node.
https://openscience.atlassian.net/browse/EMB-516
> [hotfix][EMB-516][Preprints] Put contributors back to metatags.

- CHANGELOG.md
- app/routes/content/index.js
- app/styles/app.scss
- app/templates/components/preprint-form-authors.hbs
- app/templates/submit.hbs
- package.json
- yarn.lock
Feature/node-preprint-divorce branch is not up-to-date with develop, and also needs the latest changes from pattisdr/ember-osf-preprints/feature/divorce_front_end.  Creating a PR instead of merging directly to have a more visible record of these changes.
https://openscience.atlassian.net/browse/IN-98
> Feature/Getting NPD Feature Branch up-to-date w/ Develop [IN-98]

- CHANGELOG.md
Updated changelog with divorce summary.
https://openscience.atlassian.net/browse/IN-98
> Feature/NPD Ember-osf-preprints Changelog [IN-98]

- app/controllers/submit.js
Bugfix for NPD: When editing a preprint, hitting "Save and Continue" on disciplines doesn't advance you through the form if there have been no changes
`this` was undefined when just calling `this._moveFromDisciplines`
https://openscience.atlassian.net/browse/PLAT-1248
> Fix/NPD - Advancing Discipline Section [PLAT-1248]

- app/templates/components/preprint-file-renderer.hbs
- package.json
- yarn.lock
Change render link for preprints. The bulk of the work is in the [EOSF PR](https://github.com/CenterForOpenScience/ember-osf/pull/423).
https://openscience.atlassian.net/browse/EMB-412
> [EMB-412][Preprints] Change link for rendering preprints.

- package.json
- yarn.lock
> [EMB-400] update ember-osf version

- CHANGELOG.md
Get stuff in `release/next-interfaces` into `develop`
> release/next-interfaces -> develop

- package.json
- yarn.lock
Use `feature/chronos` of `@centerforopenscience/ember-osf`.
> [EMB-535] Sse feature/chronos

- package.json
- yarn.lock
Update to use the latest navbar style changes
Update osf-style version to latest version
Should be able to test latest navbar style changes
https://openscience.atlassian.net/browse/EMB-547
> [EMB-547] Update to latest osf-style

- app/components/claim-user.js
- app/controllers/content/index.js
- app/locales/en/translations.js
- app/templates/components/claim-user.hbs
- app/templates/content/index.hbs
- package.json
- yarn.lock
Modify the claim-user component to allow claiming for logged-in users.
https://openscience.atlassian.net/browse/EMB-519
> [EMB-519][Preprints] Claim user when logged in

- app/controllers/content/index.js
- app/router.js
- app/routes/content.js
- app/routes/content/index.js
- app/routes/discover.js
- app/routes/provider.js
Changes the way we handle errors during route transition.
Comments are added in the code.
https://openscience.atlassian.net/browse/EMB-531
> [EMB-531][Preprints] API Unavailable message fix.

- app/components/claim-user.js
> [EMB-519] Dismiss modal after clicking claim.

- app/controllers/content/withdraw.js
- app/templates/content/index.hbs
Fix the problem where notice text doesn't display when the provider has no moderation.
Fix the problem where license texts doesn't break by word.
https://openscience.atlassian.net/browse/ENG-234
> [EMB-548] Fix styling and some withdraw page language

- app/components/preprint-status-banner/component.js
Use queryHasMany and make sure the newest preprint-request-action is always the first one in the query response.
https://openscience.atlassian.net/browse/ENG-559
> [ENG-559] Enforce order.

- package.json
- yarn.lock
See: https://github.com/CenterForOpenScience/ember-osf/pull/436
use ember-osf develop
Make sure special characters are not encoded in withdrawal request denial reason
https://openscience.atlassian.net/browse/ENG-743
n/a
> [ENG-743] use ember-osf develop to get request action comment fixstring

- config/environment.js
We've added `version` as custom dimension 5 to ember-osf-web and need to add it here as a placeholder.
add version as custom dimension 5
n/a
n/a
n/a
> [no ticket] add version as custom dimension 5

- app/locales/en/translations.js
- app/templates/index.hbs
Change the current link from 'requirements and roadmap' (to a google sheet) to the new roadmap page on the cos.io site
Update language for the link and the URL
https://openscience.atlassian.net/browse/ENG-738
> [ENG-738] Update link to public roadmap

- CHANGELOG.md
- config/environment.js
Clean up after #492
Remove `whiteListedProviders` from the config since it now comes from the API.
n/a
n/a
Double-check that it's unused.
> [no ticket] Remove whiteListedProviders from config

- app/controllers/content/index.js
- app/templates/content/index.hbs
- tests/unit/controllers/content/index-test.js
Use enable_chronos feature flag
Only show chronos-widget if flag is enabled for current user.
https://openscience.atlassian.net/browse/ENG-1268
> [ENG-1268]Use enable_chronos feature flag

- app/components/unregistered-contributor-form.js
> [HOTFIX ]Add swiss postfix to regex

- app/styles/author-assertions.scss
Fix COI dropdown trigger focus
Update assertion trigger css
[ENG-1730](https://openscience.atlassian.net/browse/ENG-1730)
> [ENG-1730] Fix COI dropdown trigger focus

- app/templates/submit.hbs
coi input broke as result of a bad merge conflict resolution when back merging
the latest release into develop.
- Replace `updateCoi` with `updateHasCoi`
N/A this will be tested as part of the upcoming sloan phase 2
No ticket.
> [No ticket] Update coi onchange action

- app/templates/components/multiple-textbox-input.hbs
- app/templates/submit.hbs
Adds data-test attributes to help get items in Selenium testing
- Add data-test attrs to Author Assertions and COI sections
- Add data-test attrs to multi-text inputs
There should be a data-test attributes and/or id's to use to grab elements in selenium testing
https://openscience.atlassian.net/browse/ENG-2057
> [ENG-2057] Add data-test attrs and ids for selenium testing

- app/locales/en/translations.js
- app/templates/content/index.hbs
- Remove annoying text-wrap to preprints metrics disclaimer
- add date of metrics collection start to new line
- 
> Remove annoying text-wrap

- package.json
- yarn.lock
Update Ember OSF version to fix two accessibility problems from that update.
1. Update the package.json to use the latest version of ember-osf
This has been tested already. A spot check when it goes to test should do it.
https://openscience.atlassian.net/browse/ENG-3164
https://openscience.atlassian.net/browse/ENG-3762
> [ENG-3164] [ENG-3762] Pin ember-osf to develop for testing on staging

- app/routes/index.js
- app/templates/components/preprint-navbar-branded.hbs
Reverts CenterForOpenScience/ember-osf-preprints#748. Will make a new PR to a feature branch
> Revert "[ENG-4470] Reroute users to new search page"

- app/routes/index.js
- app/templates/components/preprint-navbar-branded.hbs
This has the same content as [this previous PR](https://github.com/CenterForOpenScience/ember-osf-preprints/pull/748)
> Reroute users to new search page

- app/index.html
- config/environment.js
- ember-cli-build.js
- Add Google Tag Manager to preprints app
- Add googleTagManagerId variable and GoogleTagManager metrics adapter to environment config
- Add GoogleTagManager script to build pipeline
https://openscience.atlassian.net/browse/ENG-4598
> [ENG-4598] Add Google Tag Manager

- ember-cli-build.js
> Fix variable name mismatch

- package.json
- yarn.lock
> point to new eosf feature branch

- app/components/taxonomy-top-list.js
- Fix links in Browse by subject links
- Fix query param names for active filters 
> Fix qp values for browse by subject links

- package.json
- yarn.lock
> update eof to use 0.39.0

- app/locales/en/translations.js
> Open help link in new tab
